# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'alerts.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(341, 580)
        Form.setStyleSheet("QLabel {\n"
"    color: white;\n"
"}")
        self.widget = QtWidgets.QWidget(Form)
        self.widget.setGeometry(QtCore.QRect(0, 0, 341, 581))
        self.widget.setStyleSheet("#widget {\n"
"    background-image: url(\"img/tlo.png\");\n"
"}")
        self.widget.setObjectName("widget")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.widget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 60, 71, 491))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.led_err0 = QtWidgets.QFrame(self.verticalLayoutWidget)
        self.led_err0.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.led_err0.setFrameShadow(QtWidgets.QFrame.Raised)
        self.led_err0.setObjectName("led_err0")
        self.verticalLayout.addWidget(self.led_err0)
        self.led_err1 = QtWidgets.QFrame(self.verticalLayoutWidget)
        self.led_err1.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.led_err1.setFrameShadow(QtWidgets.QFrame.Raised)
        self.led_err1.setObjectName("led_err1")
        self.verticalLayout.addWidget(self.led_err1)
        self.led_err2 = QtWidgets.QFrame(self.verticalLayoutWidget)
        self.led_err2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.led_err2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.led_err2.setObjectName("led_err2")
        self.verticalLayout.addWidget(self.led_err2)
        self.led_err4 = QtWidgets.QFrame(self.verticalLayoutWidget)
        self.led_err4.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.led_err4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.led_err4.setObjectName("led_err4")
        self.verticalLayout.addWidget(self.led_err4)
        self.led_err5 = QtWidgets.QFrame(self.verticalLayoutWidget)
        self.led_err5.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.led_err5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.led_err5.setObjectName("led_err5")
        self.verticalLayout.addWidget(self.led_err5)
        self.led_err6 = QtWidgets.QFrame(self.verticalLayoutWidget)
        self.led_err6.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.led_err6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.led_err6.setObjectName("led_err6")
        self.verticalLayout.addWidget(self.led_err6)
        self.led_err7 = QtWidgets.QFrame(self.verticalLayoutWidget)
        self.led_err7.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.led_err7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.led_err7.setObjectName("led_err7")
        self.verticalLayout.addWidget(self.led_err7)
        self.led_err9 = QtWidgets.QFrame(self.verticalLayoutWidget)
        self.led_err9.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.led_err9.setFrameShadow(QtWidgets.QFrame.Raised)
        self.led_err9.setObjectName("led_err9")
        self.verticalLayout.addWidget(self.led_err9)
        self.led_err10 = QtWidgets.QFrame(self.verticalLayoutWidget)
        self.led_err10.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.led_err10.setFrameShadow(QtWidgets.QFrame.Raised)
        self.led_err10.setObjectName("led_err10")
        self.verticalLayout.addWidget(self.led_err10)
        self.led_err11 = QtWidgets.QFrame(self.verticalLayoutWidget)
        self.led_err11.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.led_err11.setFrameShadow(QtWidgets.QFrame.Raised)
        self.led_err11.setObjectName("led_err11")
        self.verticalLayout.addWidget(self.led_err11)
        self.led_err14 = QtWidgets.QFrame(self.verticalLayoutWidget)
        self.led_err14.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.led_err14.setFrameShadow(QtWidgets.QFrame.Raised)
        self.led_err14.setObjectName("led_err14")
        self.verticalLayout.addWidget(self.led_err14)
        self.led_err15 = QtWidgets.QFrame(self.verticalLayoutWidget)
        self.led_err15.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.led_err15.setFrameShadow(QtWidgets.QFrame.Raised)
        self.led_err15.setObjectName("led_err15")
        self.verticalLayout.addWidget(self.led_err15)
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.widget)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(90, 60, 231, 491))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_err0 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_err0.setFont(font)
        self.label_err0.setStyleSheet("")
        self.label_err0.setObjectName("label_err0")
        self.verticalLayout_2.addWidget(self.label_err0)
        self.label_err1 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_err1.setFont(font)
        self.label_err1.setStyleSheet("")
        self.label_err1.setObjectName("label_err1")
        self.verticalLayout_2.addWidget(self.label_err1)
        self.label_err2 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_err2.setFont(font)
        self.label_err2.setStyleSheet("")
        self.label_err2.setObjectName("label_err2")
        self.verticalLayout_2.addWidget(self.label_err2)
        self.label_err4 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_err4.setFont(font)
        self.label_err4.setObjectName("label_err4")
        self.verticalLayout_2.addWidget(self.label_err4)
        self.label_err5 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_err5.setFont(font)
        self.label_err5.setObjectName("label_err5")
        self.verticalLayout_2.addWidget(self.label_err5)
        self.label_err6 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_err6.setFont(font)
        self.label_err6.setObjectName("label_err6")
        self.verticalLayout_2.addWidget(self.label_err6)
        self.label_err7 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_err7.setFont(font)
        self.label_err7.setObjectName("label_err7")
        self.verticalLayout_2.addWidget(self.label_err7)
        self.label_err9 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_err9.setFont(font)
        self.label_err9.setObjectName("label_err9")
        self.verticalLayout_2.addWidget(self.label_err9)
        self.label_err10 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_err10.setFont(font)
        self.label_err10.setObjectName("label_err10")
        self.verticalLayout_2.addWidget(self.label_err10)
        self.label_err11 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_err11.setFont(font)
        self.label_err11.setObjectName("label_err11")
        self.verticalLayout_2.addWidget(self.label_err11)
        self.label_err14 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_err14.setFont(font)
        self.label_err14.setObjectName("label_err14")
        self.verticalLayout_2.addWidget(self.label_err14)
        self.label_err15 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_err15.setFont(font)
        self.label_err15.setObjectName("label_err15")
        self.verticalLayout_2.addWidget(self.label_err15)
        self.close_btn = QtWidgets.QPushButton(self.widget)
        self.close_btn.setGeometry(QtCore.QRect(10, 10, 311, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.close_btn.setFont(font)
        self.close_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.close_btn.setStyleSheet("/*background-color: qlineargradient(spread:pad, x1:0.522955, y1:0, x2:0.517, y2:1, stop:0 rgba(255, 164, 176, 255), stop:1 rgba(255, 0, 12, 255)); */\n"
"color: white;\n"
"border: 1px solid darkgrey;\n"
"border-radius: 9px;\n"
"background-color: qlineargradient(spread:pad, x1:0.522955, y1:0, x2:0.522682, y2:0.574, stop:0 rgba(255, 255, 255, 255), stop:1 rgba(255, 0, 12, 255));\n"
"background-image: none;")
        self.close_btn.setObjectName("close_btn")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_err0.setText(_translate("Form", "Identification error"))
        self.label_err1.setText(_translate("Form", "Over voltage"))
        self.label_err2.setText(_translate("Form", "Low voltage"))
        self.label_err4.setText(_translate("Form", "motor provide speed feedback"))
        self.label_err5.setText(_translate("Form", "Internal volts fault"))
        self.label_err6.setText(_translate("Form", "Over temperature"))
        self.label_err7.setText(_translate("Form", "Throttle error at power-up"))
        self.label_err9.setText(_translate("Form", "internal reset"))
        self.label_err10.setText(_translate("Form", "hall throttle open"))
        self.label_err11.setText(_translate("Form", "angle sensor open"))
        self.label_err14.setText(_translate("Form", "Motor over temperature"))
        self.label_err15.setText(_translate("Form", "Hall Galvanometer sensor error"))
        self.close_btn.setText(_translate("Form", "Close"))

