# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'src\gui\alerts.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName(_fromUtf8("Form"))
        Form.resize(341, 580)
        Form.setStyleSheet(_fromUtf8("QLabel {\n"
"    color: white;\n"
"}"))
        self.widget = QtGui.QWidget(Form)
        self.widget.setGeometry(QtCore.QRect(0, 0, 341, 581))
        self.widget.setStyleSheet(_fromUtf8("#widget {\n"
"    background-image: url(\"img/tlo.png\");\n"
"}"))
        self.widget.setObjectName(_fromUtf8("widget"))
        self.verticalLayoutWidget = QtGui.QWidget(self.widget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 60, 71, 491))
        self.verticalLayoutWidget.setObjectName(_fromUtf8("verticalLayoutWidget"))
        self.verticalLayout = QtGui.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.led_err0 = QtGui.QFrame(self.verticalLayoutWidget)
        self.led_err0.setFrameShape(QtGui.QFrame.NoFrame)
        self.led_err0.setFrameShadow(QtGui.QFrame.Raised)
        self.led_err0.setObjectName(_fromUtf8("led_err0"))
        self.verticalLayout.addWidget(self.led_err0)
        self.led_err1 = QtGui.QFrame(self.verticalLayoutWidget)
        self.led_err1.setFrameShape(QtGui.QFrame.NoFrame)
        self.led_err1.setFrameShadow(QtGui.QFrame.Raised)
        self.led_err1.setObjectName(_fromUtf8("led_err1"))
        self.verticalLayout.addWidget(self.led_err1)
        self.led_err2 = QtGui.QFrame(self.verticalLayoutWidget)
        self.led_err2.setFrameShape(QtGui.QFrame.NoFrame)
        self.led_err2.setFrameShadow(QtGui.QFrame.Raised)
        self.led_err2.setObjectName(_fromUtf8("led_err2"))
        self.verticalLayout.addWidget(self.led_err2)
        self.led_err4 = QtGui.QFrame(self.verticalLayoutWidget)
        self.led_err4.setFrameShape(QtGui.QFrame.NoFrame)
        self.led_err4.setFrameShadow(QtGui.QFrame.Raised)
        self.led_err4.setObjectName(_fromUtf8("led_err4"))
        self.verticalLayout.addWidget(self.led_err4)
        self.led_err5 = QtGui.QFrame(self.verticalLayoutWidget)
        self.led_err5.setFrameShape(QtGui.QFrame.NoFrame)
        self.led_err5.setFrameShadow(QtGui.QFrame.Raised)
        self.led_err5.setObjectName(_fromUtf8("led_err5"))
        self.verticalLayout.addWidget(self.led_err5)
        self.led_err6 = QtGui.QFrame(self.verticalLayoutWidget)
        self.led_err6.setFrameShape(QtGui.QFrame.NoFrame)
        self.led_err6.setFrameShadow(QtGui.QFrame.Raised)
        self.led_err6.setObjectName(_fromUtf8("led_err6"))
        self.verticalLayout.addWidget(self.led_err6)
        self.led_err7 = QtGui.QFrame(self.verticalLayoutWidget)
        self.led_err7.setFrameShape(QtGui.QFrame.NoFrame)
        self.led_err7.setFrameShadow(QtGui.QFrame.Raised)
        self.led_err7.setObjectName(_fromUtf8("led_err7"))
        self.verticalLayout.addWidget(self.led_err7)
        self.led_err9 = QtGui.QFrame(self.verticalLayoutWidget)
        self.led_err9.setFrameShape(QtGui.QFrame.NoFrame)
        self.led_err9.setFrameShadow(QtGui.QFrame.Raised)
        self.led_err9.setObjectName(_fromUtf8("led_err9"))
        self.verticalLayout.addWidget(self.led_err9)
        self.led_err10 = QtGui.QFrame(self.verticalLayoutWidget)
        self.led_err10.setFrameShape(QtGui.QFrame.NoFrame)
        self.led_err10.setFrameShadow(QtGui.QFrame.Raised)
        self.led_err10.setObjectName(_fromUtf8("led_err10"))
        self.verticalLayout.addWidget(self.led_err10)
        self.led_err11 = QtGui.QFrame(self.verticalLayoutWidget)
        self.led_err11.setFrameShape(QtGui.QFrame.NoFrame)
        self.led_err11.setFrameShadow(QtGui.QFrame.Raised)
        self.led_err11.setObjectName(_fromUtf8("led_err11"))
        self.verticalLayout.addWidget(self.led_err11)
        self.led_err14 = QtGui.QFrame(self.verticalLayoutWidget)
        self.led_err14.setFrameShape(QtGui.QFrame.NoFrame)
        self.led_err14.setFrameShadow(QtGui.QFrame.Raised)
        self.led_err14.setObjectName(_fromUtf8("led_err14"))
        self.verticalLayout.addWidget(self.led_err14)
        self.led_err15 = QtGui.QFrame(self.verticalLayoutWidget)
        self.led_err15.setFrameShape(QtGui.QFrame.NoFrame)
        self.led_err15.setFrameShadow(QtGui.QFrame.Raised)
        self.led_err15.setObjectName(_fromUtf8("led_err15"))
        self.verticalLayout.addWidget(self.led_err15)
        self.verticalLayoutWidget_2 = QtGui.QWidget(self.widget)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(90, 60, 231, 491))
        self.verticalLayoutWidget_2.setObjectName(_fromUtf8("verticalLayoutWidget_2"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.label_err0 = QtGui.QLabel(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_err0.setFont(font)
        self.label_err0.setStyleSheet(_fromUtf8(""))
        self.label_err0.setObjectName(_fromUtf8("label_err0"))
        self.verticalLayout_2.addWidget(self.label_err0)
        self.label_err1 = QtGui.QLabel(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_err1.setFont(font)
        self.label_err1.setStyleSheet(_fromUtf8(""))
        self.label_err1.setObjectName(_fromUtf8("label_err1"))
        self.verticalLayout_2.addWidget(self.label_err1)
        self.label_err2 = QtGui.QLabel(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_err2.setFont(font)
        self.label_err2.setStyleSheet(_fromUtf8(""))
        self.label_err2.setObjectName(_fromUtf8("label_err2"))
        self.verticalLayout_2.addWidget(self.label_err2)
        self.label_err4 = QtGui.QLabel(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_err4.setFont(font)
        self.label_err4.setObjectName(_fromUtf8("label_err4"))
        self.verticalLayout_2.addWidget(self.label_err4)
        self.label_err5 = QtGui.QLabel(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_err5.setFont(font)
        self.label_err5.setObjectName(_fromUtf8("label_err5"))
        self.verticalLayout_2.addWidget(self.label_err5)
        self.label_err6 = QtGui.QLabel(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_err6.setFont(font)
        self.label_err6.setObjectName(_fromUtf8("label_err6"))
        self.verticalLayout_2.addWidget(self.label_err6)
        self.label_err7 = QtGui.QLabel(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_err7.setFont(font)
        self.label_err7.setObjectName(_fromUtf8("label_err7"))
        self.verticalLayout_2.addWidget(self.label_err7)
        self.label_err9 = QtGui.QLabel(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_err9.setFont(font)
        self.label_err9.setObjectName(_fromUtf8("label_err9"))
        self.verticalLayout_2.addWidget(self.label_err9)
        self.label_err10 = QtGui.QLabel(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_err10.setFont(font)
        self.label_err10.setObjectName(_fromUtf8("label_err10"))
        self.verticalLayout_2.addWidget(self.label_err10)
        self.label_err11 = QtGui.QLabel(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_err11.setFont(font)
        self.label_err11.setObjectName(_fromUtf8("label_err11"))
        self.verticalLayout_2.addWidget(self.label_err11)
        self.label_err14 = QtGui.QLabel(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_err14.setFont(font)
        self.label_err14.setObjectName(_fromUtf8("label_err14"))
        self.verticalLayout_2.addWidget(self.label_err14)
        self.label_err15 = QtGui.QLabel(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_err15.setFont(font)
        self.label_err15.setObjectName(_fromUtf8("label_err15"))
        self.verticalLayout_2.addWidget(self.label_err15)
        self.close_btn = QtGui.QPushButton(self.widget)
        self.close_btn.setGeometry(QtCore.QRect(10, 10, 311, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.close_btn.setFont(font)
        self.close_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.close_btn.setStyleSheet(_fromUtf8("/*background-color: qlineargradient(spread:pad, x1:0.522955, y1:0, x2:0.517, y2:1, stop:0 rgba(255, 164, 176, 255), stop:1 rgba(255, 0, 12, 255)); */\n"
"color: white;\n"
"border: 1px solid darkgrey;\n"
"border-radius: 9px;\n"
"background-color: qlineargradient(spread:pad, x1:0.522955, y1:0, x2:0.522682, y2:0.574, stop:0 rgba(255, 255, 255, 255), stop:1 rgba(255, 0, 12, 255));\n"
"background-image: none;"))
        self.close_btn.setObjectName(_fromUtf8("close_btn"))

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        Form.setWindowTitle(_translate("Form", "Form", None))
        self.label_err0.setText(_translate("Form", "Identification error", None))
        self.label_err1.setText(_translate("Form", "Over voltage", None))
        self.label_err2.setText(_translate("Form", "Low voltage", None))
        self.label_err4.setText(_translate("Form", "motor provide speed feedback", None))
        self.label_err5.setText(_translate("Form", "Internal volts fault", None))
        self.label_err6.setText(_translate("Form", "Over temperature", None))
        self.label_err7.setText(_translate("Form", "Throttle error at power-up", None))
        self.label_err9.setText(_translate("Form", "internal reset", None))
        self.label_err10.setText(_translate("Form", "hall throttle open", None))
        self.label_err11.setText(_translate("Form", "angle sensor open", None))
        self.label_err14.setText(_translate("Form", "Motor over temperature", None))
        self.label_err15.setText(_translate("Form", "Hall Galvanometer sensor error", None))
        self.close_btn.setText(_translate("Form", "Close", None))

