# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'rpm_widget.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_rpm_widget(object):
    def setupUi(self, rpm_widget):
        rpm_widget.setObjectName("rpm_widget")
        rpm_widget.resize(301, 301)
        rpm_widget.setStyleSheet("background: none;")
        self.rpmCaption = QtWidgets.QLabel(rpm_widget)
        self.rpmCaption.setGeometry(QtCore.QRect(120, 240, 51, 21))
        font = QtGui.QFont()
        font.setFamily("Gill Sans MT")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(9)
        self.rpmCaption.setFont(font)
        self.rpmCaption.setStyleSheet("color: white; \n"
"background:none;\n"
"font: 75 italic 14pt \"Gill Sans MT\" ;\n"
"color: rgb(216, 216, 216);")
        self.rpmCaption.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.rpmCaption.setObjectName("rpmCaption")
        self.graphicsView = QtWidgets.QGraphicsView(rpm_widget)
        self.graphicsView.setGeometry(QtCore.QRect(0, 0, 301, 301))
        self.graphicsView.setStyleSheet("background: transparent; ")
        self.graphicsView.setObjectName("graphicsView")
        self.rpmNumber = QtWidgets.QLCDNumber(rpm_widget)
        self.rpmNumber.setGeometry(QtCore.QRect(74, 173, 151, 61))
        self.rpmNumber.setStyleSheet("color: yellow;\n"
"background-color: rgba(255, 255, 255, 20)")
        self.rpmNumber.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.rpmNumber.setDigitCount(5)
        self.rpmNumber.setObjectName("rpmNumber")
        self.black_circle = QtWidgets.QLabel(rpm_widget)
        self.black_circle.setGeometry(QtCore.QRect(0, 0, 301, 301))
        self.black_circle.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.black_circle.setStyleSheet("background-color: none;")
        self.black_circle.setFrameShape(QtWidgets.QFrame.Box)
        self.black_circle.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.black_circle.setText("")
        self.black_circle.setPixmap(QtGui.QPixmap("img/blackcircle.png"))
        self.black_circle.setScaledContents(True)
        self.black_circle.setObjectName("black_circle")
        self.dots_widget = QtWidgets.QWidget(rpm_widget)
        self.dots_widget.setEnabled(True)
        self.dots_widget.setGeometry(QtCore.QRect(0, 0, 301, 301))
        self.dots_widget.setObjectName("dots_widget")
        self.circle1 = QtWidgets.QLabel(self.dots_widget)
        self.circle1.setGeometry(QtCore.QRect(14, 195, 31, 31))
        self.circle1.setText("")
        self.circle1.setPixmap(QtGui.QPixmap("img/colorized_circles/circle1.png"))
        self.circle1.setScaledContents(True)
        self.circle1.setObjectName("circle1")
        self.circle2 = QtWidgets.QLabel(self.dots_widget)
        self.circle2.setGeometry(QtCore.QRect(7, 172, 31, 31))
        self.circle2.setText("")
        self.circle2.setPixmap(QtGui.QPixmap("img/colorized_circles/circle2.png"))
        self.circle2.setScaledContents(True)
        self.circle2.setObjectName("circle2")
        self.circle3 = QtWidgets.QLabel(self.dots_widget)
        self.circle3.setGeometry(QtCore.QRect(1, 148, 31, 31))
        self.circle3.setText("")
        self.circle3.setPixmap(QtGui.QPixmap("img/colorized_circles/circle3.png"))
        self.circle3.setScaledContents(True)
        self.circle3.setObjectName("circle3")
        self.circle4 = QtWidgets.QLabel(self.dots_widget)
        self.circle4.setGeometry(QtCore.QRect(2, 124, 31, 31))
        self.circle4.setText("")
        self.circle4.setPixmap(QtGui.QPixmap("img/colorized_circles/circle4.png"))
        self.circle4.setScaledContents(True)
        self.circle4.setObjectName("circle4")
        self.circle5 = QtWidgets.QLabel(self.dots_widget)
        self.circle5.setGeometry(QtCore.QRect(8, 99, 31, 31))
        self.circle5.setText("")
        self.circle5.setPixmap(QtGui.QPixmap("img/colorized_circles/circle5.png"))
        self.circle5.setScaledContents(True)
        self.circle5.setObjectName("circle5")
        self.circle6 = QtWidgets.QLabel(self.dots_widget)
        self.circle6.setGeometry(QtCore.QRect(18, 75, 31, 31))
        self.circle6.setText("")
        self.circle6.setPixmap(QtGui.QPixmap("img/colorized_circles/circle6.png"))
        self.circle6.setScaledContents(True)
        self.circle6.setObjectName("circle6")
        self.circle7 = QtWidgets.QLabel(self.dots_widget)
        self.circle7.setGeometry(QtCore.QRect(31, 54, 31, 31))
        self.circle7.setText("")
        self.circle7.setPixmap(QtGui.QPixmap("img/colorized_circles/circle7.png"))
        self.circle7.setScaledContents(True)
        self.circle7.setObjectName("circle7")
        self.circle8 = QtWidgets.QLabel(self.dots_widget)
        self.circle8.setGeometry(QtCore.QRect(48, 36, 31, 31))
        self.circle8.setText("")
        self.circle8.setPixmap(QtGui.QPixmap("img/colorized_circles/circle8.png"))
        self.circle8.setScaledContents(True)
        self.circle8.setObjectName("circle8")
        self.circle9 = QtWidgets.QLabel(self.dots_widget)
        self.circle9.setGeometry(QtCore.QRect(68, 21, 31, 31))
        self.circle9.setStyleSheet("")
        self.circle9.setText("")
        self.circle9.setPixmap(QtGui.QPixmap("img/colorized_circles/circle9.png"))
        self.circle9.setScaledContents(True)
        self.circle9.setObjectName("circle9")
        self.circle10 = QtWidgets.QLabel(self.dots_widget)
        self.circle10.setGeometry(QtCore.QRect(89, 11, 31, 31))
        self.circle10.setText("")
        self.circle10.setPixmap(QtGui.QPixmap("img/colorized_circles/circle10.png"))
        self.circle10.setScaledContents(True)
        self.circle10.setObjectName("circle10")
        self.circle11 = QtWidgets.QLabel(self.dots_widget)
        self.circle11.setEnabled(True)
        self.circle11.setGeometry(QtCore.QRect(112, 4, 31, 31))
        self.circle11.setText("")
        self.circle11.setPixmap(QtGui.QPixmap("img/colorized_circles/circle11.png"))
        self.circle11.setScaledContents(True)
        self.circle11.setObjectName("circle11")
        self.circle12 = QtWidgets.QLabel(self.dots_widget)
        self.circle12.setGeometry(QtCore.QRect(136, 1, 31, 31))
        self.circle12.setText("")
        self.circle12.setPixmap(QtGui.QPixmap("img/colorized_circles/circle12.png"))
        self.circle12.setScaledContents(True)
        self.circle12.setObjectName("circle12")
        self.circle13 = QtWidgets.QLabel(self.dots_widget)
        self.circle13.setGeometry(QtCore.QRect(159, 5, 31, 31))
        self.circle13.setText("")
        self.circle13.setPixmap(QtGui.QPixmap("img/colorized_circles/circle13.png"))
        self.circle13.setScaledContents(True)
        self.circle13.setObjectName("circle13")
        self.circle14 = QtWidgets.QLabel(self.dots_widget)
        self.circle14.setGeometry(QtCore.QRect(182, 11, 31, 31))
        self.circle14.setText("")
        self.circle14.setPixmap(QtGui.QPixmap("img/colorized_circles/circle14.png"))
        self.circle14.setScaledContents(True)
        self.circle14.setObjectName("circle14")
        self.circle15 = QtWidgets.QLabel(self.dots_widget)
        self.circle15.setGeometry(QtCore.QRect(205, 21, 31, 31))
        self.circle15.setText("")
        self.circle15.setPixmap(QtGui.QPixmap("img/colorized_circles/circle15.png"))
        self.circle15.setScaledContents(True)
        self.circle15.setObjectName("circle15")
        self.circle16 = QtWidgets.QLabel(self.dots_widget)
        self.circle16.setGeometry(QtCore.QRect(224, 37, 31, 31))
        self.circle16.setText("")
        self.circle16.setPixmap(QtGui.QPixmap("img/colorized_circles/circle16.png"))
        self.circle16.setScaledContents(True)
        self.circle16.setObjectName("circle16")
        self.circle17 = QtWidgets.QLabel(self.dots_widget)
        self.circle17.setGeometry(QtCore.QRect(241, 55, 31, 31))
        self.circle17.setText("")
        self.circle17.setPixmap(QtGui.QPixmap("img/colorized_circles/circle17.png"))
        self.circle17.setScaledContents(True)
        self.circle17.setObjectName("circle17")
        self.circle18 = QtWidgets.QLabel(self.dots_widget)
        self.circle18.setGeometry(QtCore.QRect(253, 75, 31, 31))
        self.circle18.setText("")
        self.circle18.setPixmap(QtGui.QPixmap("img/colorized_circles/circle18.png"))
        self.circle18.setScaledContents(True)
        self.circle18.setObjectName("circle18")
        self.circle19 = QtWidgets.QLabel(self.dots_widget)
        self.circle19.setGeometry(QtCore.QRect(263, 98, 31, 31))
        self.circle19.setText("")
        self.circle19.setPixmap(QtGui.QPixmap("img/colorized_circles/circle19.png"))
        self.circle19.setScaledContents(True)
        self.circle19.setObjectName("circle19")
        self.circle20 = QtWidgets.QLabel(self.dots_widget)
        self.circle20.setGeometry(QtCore.QRect(269, 121, 31, 31))
        self.circle20.setText("")
        self.circle20.setPixmap(QtGui.QPixmap("img/colorized_circles/circle20.png"))
        self.circle20.setScaledContents(True)
        self.circle20.setObjectName("circle20")
        self.circle21 = QtWidgets.QLabel(self.dots_widget)
        self.circle21.setGeometry(QtCore.QRect(270, 145, 31, 31))
        self.circle21.setText("")
        self.circle21.setPixmap(QtGui.QPixmap("img/colorized_circles/circle21.png"))
        self.circle21.setScaledContents(True)
        self.circle21.setObjectName("circle21")
        self.circle22 = QtWidgets.QLabel(self.dots_widget)
        self.circle22.setGeometry(QtCore.QRect(266, 169, 31, 31))
        self.circle22.setText("")
        self.circle22.setPixmap(QtGui.QPixmap("img/colorized_circles/circle22.png"))
        self.circle22.setScaledContents(True)
        self.circle22.setObjectName("circle22")
        self.circle23 = QtWidgets.QLabel(self.dots_widget)
        self.circle23.setGeometry(QtCore.QRect(257, 191, 31, 31))
        self.circle23.setText("")
        self.circle23.setPixmap(QtGui.QPixmap("img/colorized_circles/circle23.png"))
        self.circle23.setScaledContents(True)
        self.circle23.setObjectName("circle23")
        self.pintop = QtWidgets.QLabel(rpm_widget)
        self.pintop.setGeometry(QtCore.QRect(130, 130, 41, 41))
        self.pintop.setStyleSheet("background: none;")
        self.pintop.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.pintop.setText("")
        self.pintop.setPixmap(QtGui.QPixmap("img/pintop.png"))
        self.pintop.setScaledContents(True)
        self.pintop.setObjectName("pintop")
        self.dark_dots_widget = QtWidgets.QWidget(rpm_widget)
        self.dark_dots_widget.setEnabled(True)
        self.dark_dots_widget.setGeometry(QtCore.QRect(0, 0, 301, 301))
        self.dark_dots_widget.setObjectName("dark_dots_widget")
        self.circle1_3 = QtWidgets.QLabel(self.dark_dots_widget)
        self.circle1_3.setGeometry(QtCore.QRect(14, 195, 31, 31))
        self.circle1_3.setText("")
        self.circle1_3.setPixmap(QtGui.QPixmap("img/dark_colorized_circles/circle1.png"))
        self.circle1_3.setScaledContents(True)
        self.circle1_3.setObjectName("circle1_3")
        self.circle2_3 = QtWidgets.QLabel(self.dark_dots_widget)
        self.circle2_3.setGeometry(QtCore.QRect(7, 172, 31, 31))
        self.circle2_3.setText("")
        self.circle2_3.setPixmap(QtGui.QPixmap("img/dark_colorized_circles/circle2.png"))
        self.circle2_3.setScaledContents(True)
        self.circle2_3.setObjectName("circle2_3")
        self.circle3_3 = QtWidgets.QLabel(self.dark_dots_widget)
        self.circle3_3.setGeometry(QtCore.QRect(1, 148, 31, 31))
        self.circle3_3.setText("")
        self.circle3_3.setPixmap(QtGui.QPixmap("img/dark_colorized_circles/circle3.png"))
        self.circle3_3.setScaledContents(True)
        self.circle3_3.setObjectName("circle3_3")
        self.circle4_3 = QtWidgets.QLabel(self.dark_dots_widget)
        self.circle4_3.setGeometry(QtCore.QRect(2, 124, 31, 31))
        self.circle4_3.setText("")
        self.circle4_3.setPixmap(QtGui.QPixmap("img/dark_colorized_circles/circle4.png"))
        self.circle4_3.setScaledContents(True)
        self.circle4_3.setObjectName("circle4_3")
        self.circle5_3 = QtWidgets.QLabel(self.dark_dots_widget)
        self.circle5_3.setGeometry(QtCore.QRect(8, 99, 31, 31))
        self.circle5_3.setText("")
        self.circle5_3.setPixmap(QtGui.QPixmap("img/dark_colorized_circles/circle5.png"))
        self.circle5_3.setScaledContents(True)
        self.circle5_3.setObjectName("circle5_3")
        self.circle6_3 = QtWidgets.QLabel(self.dark_dots_widget)
        self.circle6_3.setGeometry(QtCore.QRect(18, 75, 31, 31))
        self.circle6_3.setText("")
        self.circle6_3.setPixmap(QtGui.QPixmap("img/dark_colorized_circles/circle6.png"))
        self.circle6_3.setScaledContents(True)
        self.circle6_3.setObjectName("circle6_3")
        self.circle7_3 = QtWidgets.QLabel(self.dark_dots_widget)
        self.circle7_3.setGeometry(QtCore.QRect(31, 54, 31, 31))
        self.circle7_3.setText("")
        self.circle7_3.setPixmap(QtGui.QPixmap("img/dark_colorized_circles/circle7.png"))
        self.circle7_3.setScaledContents(True)
        self.circle7_3.setObjectName("circle7_3")
        self.circle8_3 = QtWidgets.QLabel(self.dark_dots_widget)
        self.circle8_3.setGeometry(QtCore.QRect(48, 36, 31, 31))
        self.circle8_3.setText("")
        self.circle8_3.setPixmap(QtGui.QPixmap("img/dark_colorized_circles/circle8.png"))
        self.circle8_3.setScaledContents(True)
        self.circle8_3.setObjectName("circle8_3")
        self.circle9_3 = QtWidgets.QLabel(self.dark_dots_widget)
        self.circle9_3.setGeometry(QtCore.QRect(68, 21, 31, 31))
        self.circle9_3.setStyleSheet("")
        self.circle9_3.setText("")
        self.circle9_3.setPixmap(QtGui.QPixmap("img/dark_colorized_circles/circle9.png"))
        self.circle9_3.setScaledContents(True)
        self.circle9_3.setObjectName("circle9_3")
        self.circle10_3 = QtWidgets.QLabel(self.dark_dots_widget)
        self.circle10_3.setGeometry(QtCore.QRect(89, 11, 31, 31))
        self.circle10_3.setText("")
        self.circle10_3.setPixmap(QtGui.QPixmap("img/dark_colorized_circles/circle10.png"))
        self.circle10_3.setScaledContents(True)
        self.circle10_3.setObjectName("circle10_3")
        self.circle11_3 = QtWidgets.QLabel(self.dark_dots_widget)
        self.circle11_3.setEnabled(True)
        self.circle11_3.setGeometry(QtCore.QRect(112, 4, 31, 31))
        self.circle11_3.setText("")
        self.circle11_3.setPixmap(QtGui.QPixmap("img/dark_colorized_circles/circle11.png"))
        self.circle11_3.setScaledContents(True)
        self.circle11_3.setObjectName("circle11_3")
        self.circle12_3 = QtWidgets.QLabel(self.dark_dots_widget)
        self.circle12_3.setGeometry(QtCore.QRect(136, 1, 31, 31))
        self.circle12_3.setText("")
        self.circle12_3.setPixmap(QtGui.QPixmap("img/dark_colorized_circles/circle12.png"))
        self.circle12_3.setScaledContents(True)
        self.circle12_3.setObjectName("circle12_3")
        self.circle13_3 = QtWidgets.QLabel(self.dark_dots_widget)
        self.circle13_3.setGeometry(QtCore.QRect(159, 5, 31, 31))
        self.circle13_3.setText("")
        self.circle13_3.setPixmap(QtGui.QPixmap("img/dark_colorized_circles/circle13.png"))
        self.circle13_3.setScaledContents(True)
        self.circle13_3.setObjectName("circle13_3")
        self.circle14_3 = QtWidgets.QLabel(self.dark_dots_widget)
        self.circle14_3.setGeometry(QtCore.QRect(182, 11, 31, 31))
        self.circle14_3.setText("")
        self.circle14_3.setPixmap(QtGui.QPixmap("img/dark_colorized_circles/circle14.png"))
        self.circle14_3.setScaledContents(True)
        self.circle14_3.setObjectName("circle14_3")
        self.circle15_3 = QtWidgets.QLabel(self.dark_dots_widget)
        self.circle15_3.setGeometry(QtCore.QRect(205, 21, 31, 31))
        self.circle15_3.setText("")
        self.circle15_3.setPixmap(QtGui.QPixmap("img/dark_colorized_circles/circle15.png"))
        self.circle15_3.setScaledContents(True)
        self.circle15_3.setObjectName("circle15_3")
        self.circle16_3 = QtWidgets.QLabel(self.dark_dots_widget)
        self.circle16_3.setGeometry(QtCore.QRect(224, 37, 31, 31))
        self.circle16_3.setText("")
        self.circle16_3.setPixmap(QtGui.QPixmap("img/dark_colorized_circles/circle16.png"))
        self.circle16_3.setScaledContents(True)
        self.circle16_3.setObjectName("circle16_3")
        self.circle17_3 = QtWidgets.QLabel(self.dark_dots_widget)
        self.circle17_3.setGeometry(QtCore.QRect(241, 55, 31, 31))
        self.circle17_3.setText("")
        self.circle17_3.setPixmap(QtGui.QPixmap("img/dark_colorized_circles/circle17.png"))
        self.circle17_3.setScaledContents(True)
        self.circle17_3.setObjectName("circle17_3")
        self.circle18_3 = QtWidgets.QLabel(self.dark_dots_widget)
        self.circle18_3.setGeometry(QtCore.QRect(253, 75, 31, 31))
        self.circle18_3.setText("")
        self.circle18_3.setPixmap(QtGui.QPixmap("img/dark_colorized_circles/circle18.png"))
        self.circle18_3.setScaledContents(True)
        self.circle18_3.setObjectName("circle18_3")
        self.circle19_3 = QtWidgets.QLabel(self.dark_dots_widget)
        self.circle19_3.setGeometry(QtCore.QRect(263, 98, 31, 31))
        self.circle19_3.setText("")
        self.circle19_3.setPixmap(QtGui.QPixmap("img/dark_colorized_circles/circle19.png"))
        self.circle19_3.setScaledContents(True)
        self.circle19_3.setObjectName("circle19_3")
        self.circle20_3 = QtWidgets.QLabel(self.dark_dots_widget)
        self.circle20_3.setGeometry(QtCore.QRect(269, 121, 31, 31))
        self.circle20_3.setText("")
        self.circle20_3.setPixmap(QtGui.QPixmap("img/dark_colorized_circles/circle20.png"))
        self.circle20_3.setScaledContents(True)
        self.circle20_3.setObjectName("circle20_3")
        self.circle21_3 = QtWidgets.QLabel(self.dark_dots_widget)
        self.circle21_3.setGeometry(QtCore.QRect(270, 145, 31, 31))
        self.circle21_3.setText("")
        self.circle21_3.setPixmap(QtGui.QPixmap("img/dark_colorized_circles/circle21.png"))
        self.circle21_3.setScaledContents(True)
        self.circle21_3.setObjectName("circle21_3")
        self.circle22_3 = QtWidgets.QLabel(self.dark_dots_widget)
        self.circle22_3.setGeometry(QtCore.QRect(266, 169, 31, 31))
        self.circle22_3.setText("")
        self.circle22_3.setPixmap(QtGui.QPixmap("img/dark_colorized_circles/circle22.png"))
        self.circle22_3.setScaledContents(True)
        self.circle22_3.setObjectName("circle22_3")
        self.circle23_3 = QtWidgets.QLabel(self.dark_dots_widget)
        self.circle23_3.setGeometry(QtCore.QRect(257, 191, 31, 31))
        self.circle23_3.setText("")
        self.circle23_3.setPixmap(QtGui.QPixmap("img/dark_colorized_circles/circle23.png"))
        self.circle23_3.setScaledContents(True)
        self.circle23_3.setObjectName("circle23_3")
        self.rpmCaption_2 = QtWidgets.QLabel(rpm_widget)
        self.rpmCaption_2.setGeometry(QtCore.QRect(30, 130, 20, 20))
        font = QtGui.QFont()
        font.setFamily("Gill Sans MT")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(9)
        self.rpmCaption_2.setFont(font)
        self.rpmCaption_2.setStyleSheet("color: white; \n"
"background:none;\n"
"font: 75 italic 12pt \"Gill Sans MT\" ;\n"
"color: rgb(216, 216, 216);")
        self.rpmCaption_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.rpmCaption_2.setObjectName("rpmCaption_2")
        self.rpmCaption_3 = QtWidgets.QLabel(rpm_widget)
        self.rpmCaption_3.setGeometry(QtCore.QRect(70, 60, 20, 20))
        font = QtGui.QFont()
        font.setFamily("Gill Sans MT")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(9)
        self.rpmCaption_3.setFont(font)
        self.rpmCaption_3.setStyleSheet("color: white; \n"
"background:none;\n"
"font: 75 italic 12pt \"Gill Sans MT\" ;\n"
"color: rgb(216, 216, 216);")
        self.rpmCaption_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.rpmCaption_3.setObjectName("rpmCaption_3")
        self.rpmCaption_4 = QtWidgets.QLabel(rpm_widget)
        self.rpmCaption_4.setGeometry(QtCore.QRect(140, 40, 16, 16))
        font = QtGui.QFont()
        font.setFamily("Gill Sans MT")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(9)
        self.rpmCaption_4.setFont(font)
        self.rpmCaption_4.setStyleSheet("color: white; \n"
"background:none;\n"
"font: 75 italic 12pt \"Gill Sans MT\" ;\n"
"color: rgb(216, 216, 216);")
        self.rpmCaption_4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.rpmCaption_4.setObjectName("rpmCaption_4")
        self.rpmCaption_5 = QtWidgets.QLabel(rpm_widget)
        self.rpmCaption_5.setGeometry(QtCore.QRect(200, 60, 20, 20))
        font = QtGui.QFont()
        font.setFamily("Gill Sans MT")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(9)
        self.rpmCaption_5.setFont(font)
        self.rpmCaption_5.setStyleSheet("color: white; \n"
"background:none;\n"
"font: 75 italic 12pt \"Gill Sans MT\" ;\n"
"color: rgb(216, 216, 216);")
        self.rpmCaption_5.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.rpmCaption_5.setObjectName("rpmCaption_5")
        self.rpmCaption_6 = QtWidgets.QLabel(rpm_widget)
        self.rpmCaption_6.setGeometry(QtCore.QRect(240, 130, 20, 21))
        font = QtGui.QFont()
        font.setFamily("Gill Sans MT")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(9)
        self.rpmCaption_6.setFont(font)
        self.rpmCaption_6.setStyleSheet("color: white; \n"
"background:none;\n"
"font: 75 italic 12pt \"Gill Sans MT\" ;\n"
"color: rgb(216, 216, 216);")
        self.rpmCaption_6.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.rpmCaption_6.setObjectName("rpmCaption_6")
        self.rpmCaption_7 = QtWidgets.QLabel(rpm_widget)
        self.rpmCaption_7.setGeometry(QtCore.QRect(230, 200, 20, 21))
        font = QtGui.QFont()
        font.setFamily("Gill Sans MT")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(9)
        self.rpmCaption_7.setFont(font)
        self.rpmCaption_7.setStyleSheet("color: white; \n"
"background:none;\n"
"font: 75 italic 12pt \"Gill Sans MT\" ;\n"
"color: rgb(216, 216, 216);")
        self.rpmCaption_7.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.rpmCaption_7.setObjectName("rpmCaption_7")
        self.rpmCaption_8 = QtWidgets.QLabel(rpm_widget)
        self.rpmCaption_8.setGeometry(QtCore.QRect(110, 100, 91, 21))
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        self.rpmCaption_8.setFont(font)
        self.rpmCaption_8.setStyleSheet("color: white; \n"
"font: 14pt \"Ubuntu Mono\";\n"
"background:none;\n"
"font: 63 italic 14pt \"Ubuntu\";\n"
"color: rgb(216, 216, 216);\n"
"font: italic 14pt \"Ubuntu\";")
        self.rpmCaption_8.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.rpmCaption_8.setObjectName("rpmCaption_8")
        self.black_circle.raise_()
        self.dark_dots_widget.raise_()
        self.dots_widget.raise_()
        self.graphicsView.raise_()
        self.pintop.raise_()
        self.rpmCaption.raise_()
        self.rpmNumber.raise_()
        self.rpmCaption_2.raise_()
        self.rpmCaption_3.raise_()
        self.rpmCaption_4.raise_()
        self.rpmCaption_5.raise_()
        self.rpmCaption_6.raise_()
        self.rpmCaption_7.raise_()
        self.rpmCaption_8.raise_()

        self.retranslateUi(rpm_widget)
        QtCore.QMetaObject.connectSlotsByName(rpm_widget)

    def retranslateUi(self, rpm_widget):
        _translate = QtCore.QCoreApplication.translate
        rpm_widget.setWindowTitle(_translate("rpm_widget", "Form"))
        self.rpmCaption.setText(_translate("rpm_widget", "km/h"))
        self.rpmCaption_2.setText(_translate("rpm_widget", "1"))
        self.rpmCaption_3.setText(_translate("rpm_widget", "2"))
        self.rpmCaption_4.setText(_translate("rpm_widget", "3"))
        self.rpmCaption_5.setText(_translate("rpm_widget", "4"))
        self.rpmCaption_6.setText(_translate("rpm_widget", "5"))
        self.rpmCaption_7.setText(_translate("rpm_widget", "6"))
        self.rpmCaption_8.setText(_translate("rpm_widget", "rpm * 1000"))

