# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'rpm_widget.ui'
#
# Created: Tue Sep 19 17:46:59 2017
#      by: PyQt4 UI code generator 4.11.2
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_rpm_widget(object):
    def setupUi(self, rpm_widget):
        rpm_widget.setObjectName(_fromUtf8("rpm_widget"))
        rpm_widget.resize(301, 301)
        rpm_widget.setStyleSheet(_fromUtf8("background: none;"))
        self.black_circle = QtGui.QLabel(rpm_widget)
        self.black_circle.setGeometry(QtCore.QRect(0, 0, 301, 301))
        self.black_circle.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.black_circle.setStyleSheet(_fromUtf8("background-color: none;"))
        self.black_circle.setFrameShape(QtGui.QFrame.Box)
        self.black_circle.setFrameShadow(QtGui.QFrame.Sunken)
        self.black_circle.setText(_fromUtf8(""))
        self.black_circle.setPixmap(QtGui.QPixmap(_fromUtf8("img/blackcircle.png")))
        self.black_circle.setScaledContents(True)
        self.black_circle.setObjectName(_fromUtf8("black_circle"))
        self.rpmCaption = QtGui.QLabel(rpm_widget)
        self.rpmCaption.setGeometry(QtCore.QRect(50, 238, 191, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Levenim MT"))
        font.setPointSize(18)
        self.rpmCaption.setFont(font)
        self.rpmCaption.setStyleSheet(_fromUtf8("color: white; background:none;"))
        self.rpmCaption.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.rpmCaption.setObjectName(_fromUtf8("rpmCaption"))
        self.graphicsView = QtGui.QGraphicsView(rpm_widget)
        self.graphicsView.setGeometry(QtCore.QRect(0, 0, 301, 301))
        self.graphicsView.setStyleSheet(_fromUtf8("background: transparent; "))
        self.graphicsView.setObjectName(_fromUtf8("graphicsView"))
        self.rpmNumber = QtGui.QLCDNumber(rpm_widget)
        self.rpmNumber.setGeometry(QtCore.QRect(74, 173, 151, 61))
        self.rpmNumber.setStyleSheet(_fromUtf8("color: yellow;\n"
"background-color: rgba(255, 255, 255, 20)"))
        self.rpmNumber.setFrameShape(QtGui.QFrame.NoFrame)
        self.rpmNumber.setDigitCount(5)
        self.rpmNumber.setObjectName(_fromUtf8("rpmNumber"))
        self.dots_widget = QtGui.QWidget(rpm_widget)
        self.dots_widget.setEnabled(True)
        self.dots_widget.setGeometry(QtCore.QRect(0, 0, 301, 301))
        self.dots_widget.setObjectName(_fromUtf8("dots_widget"))
        self.circle1 = QtGui.QLabel(self.dots_widget)
        self.circle1.setGeometry(QtCore.QRect(14, 195, 31, 31))
        self.circle1.setText(_fromUtf8(""))
        self.circle1.setPixmap(QtGui.QPixmap(_fromUtf8("img/colorized_circles/circle1.png")))
        self.circle1.setScaledContents(True)
        self.circle1.setObjectName(_fromUtf8("circle1"))
        self.circle2 = QtGui.QLabel(self.dots_widget)
        self.circle2.setGeometry(QtCore.QRect(7, 172, 31, 31))
        self.circle2.setText(_fromUtf8(""))
        self.circle2.setPixmap(QtGui.QPixmap(_fromUtf8("img/colorized_circles/circle2.png")))
        self.circle2.setScaledContents(True)
        self.circle2.setObjectName(_fromUtf8("circle2"))
        self.circle3 = QtGui.QLabel(self.dots_widget)
        self.circle3.setGeometry(QtCore.QRect(1, 148, 31, 31))
        self.circle3.setText(_fromUtf8(""))
        self.circle3.setPixmap(QtGui.QPixmap(_fromUtf8("img/colorized_circles/circle3.png")))
        self.circle3.setScaledContents(True)
        self.circle3.setObjectName(_fromUtf8("circle3"))
        self.circle4 = QtGui.QLabel(self.dots_widget)
        self.circle4.setGeometry(QtCore.QRect(2, 124, 31, 31))
        self.circle4.setText(_fromUtf8(""))
        self.circle4.setPixmap(QtGui.QPixmap(_fromUtf8("img/colorized_circles/circle4.png")))
        self.circle4.setScaledContents(True)
        self.circle4.setObjectName(_fromUtf8("circle4"))
        self.circle5 = QtGui.QLabel(self.dots_widget)
        self.circle5.setGeometry(QtCore.QRect(8, 99, 31, 31))
        self.circle5.setText(_fromUtf8(""))
        self.circle5.setPixmap(QtGui.QPixmap(_fromUtf8("img/colorized_circles/circle5.png")))
        self.circle5.setScaledContents(True)
        self.circle5.setObjectName(_fromUtf8("circle5"))
        self.circle6 = QtGui.QLabel(self.dots_widget)
        self.circle6.setGeometry(QtCore.QRect(18, 75, 31, 31))
        self.circle6.setText(_fromUtf8(""))
        self.circle6.setPixmap(QtGui.QPixmap(_fromUtf8("img/colorized_circles/circle6.png")))
        self.circle6.setScaledContents(True)
        self.circle6.setObjectName(_fromUtf8("circle6"))
        self.circle7 = QtGui.QLabel(self.dots_widget)
        self.circle7.setGeometry(QtCore.QRect(31, 54, 31, 31))
        self.circle7.setText(_fromUtf8(""))
        self.circle7.setPixmap(QtGui.QPixmap(_fromUtf8("img/colorized_circles/circle7.png")))
        self.circle7.setScaledContents(True)
        self.circle7.setObjectName(_fromUtf8("circle7"))
        self.circle8 = QtGui.QLabel(self.dots_widget)
        self.circle8.setGeometry(QtCore.QRect(48, 36, 31, 31))
        self.circle8.setText(_fromUtf8(""))
        self.circle8.setPixmap(QtGui.QPixmap(_fromUtf8("img/colorized_circles/circle8.png")))
        self.circle8.setScaledContents(True)
        self.circle8.setObjectName(_fromUtf8("circle8"))
        self.circle9 = QtGui.QLabel(self.dots_widget)
        self.circle9.setGeometry(QtCore.QRect(68, 21, 31, 31))
        self.circle9.setText(_fromUtf8(""))
        self.circle9.setPixmap(QtGui.QPixmap(_fromUtf8("img/colorized_circles/circle9.png")))
        self.circle9.setScaledContents(True)
        self.circle9.setObjectName(_fromUtf8("circle9"))
        self.circle10 = QtGui.QLabel(self.dots_widget)
        self.circle10.setGeometry(QtCore.QRect(89, 11, 31, 31))
        self.circle10.setText(_fromUtf8(""))
        self.circle10.setPixmap(QtGui.QPixmap(_fromUtf8("img/colorized_circles/circle10.png")))
        self.circle10.setScaledContents(True)
        self.circle10.setObjectName(_fromUtf8("circle10"))
        self.circle11 = QtGui.QLabel(self.dots_widget)
        self.circle11.setEnabled(True)
        self.circle11.setGeometry(QtCore.QRect(112, 4, 31, 31))
        self.circle11.setText(_fromUtf8(""))
        self.circle11.setPixmap(QtGui.QPixmap(_fromUtf8("img/colorized_circles/circle11.png")))
        self.circle11.setScaledContents(True)
        self.circle11.setObjectName(_fromUtf8("circle11"))
        self.circle12 = QtGui.QLabel(self.dots_widget)
        self.circle12.setGeometry(QtCore.QRect(136, 1, 31, 31))
        self.circle12.setText(_fromUtf8(""))
        self.circle12.setPixmap(QtGui.QPixmap(_fromUtf8("img/colorized_circles/circle12.png")))
        self.circle12.setScaledContents(True)
        self.circle12.setObjectName(_fromUtf8("circle12"))
        self.circle13 = QtGui.QLabel(self.dots_widget)
        self.circle13.setGeometry(QtCore.QRect(159, 5, 31, 31))
        self.circle13.setText(_fromUtf8(""))
        self.circle13.setPixmap(QtGui.QPixmap(_fromUtf8("img/colorized_circles/circle13.png")))
        self.circle13.setScaledContents(True)
        self.circle13.setObjectName(_fromUtf8("circle13"))
        self.circle14 = QtGui.QLabel(self.dots_widget)
        self.circle14.setGeometry(QtCore.QRect(182, 11, 31, 31))
        self.circle14.setText(_fromUtf8(""))
        self.circle14.setPixmap(QtGui.QPixmap(_fromUtf8("img/colorized_circles/circle14.png")))
        self.circle14.setScaledContents(True)
        self.circle14.setObjectName(_fromUtf8("circle14"))
        self.circle15 = QtGui.QLabel(self.dots_widget)
        self.circle15.setGeometry(QtCore.QRect(205, 21, 31, 31))
        self.circle15.setText(_fromUtf8(""))
        self.circle15.setPixmap(QtGui.QPixmap(_fromUtf8("img/colorized_circles/circle15.png")))
        self.circle15.setScaledContents(True)
        self.circle15.setObjectName(_fromUtf8("circle15"))
        self.circle16 = QtGui.QLabel(self.dots_widget)
        self.circle16.setGeometry(QtCore.QRect(224, 37, 31, 31))
        self.circle16.setText(_fromUtf8(""))
        self.circle16.setPixmap(QtGui.QPixmap(_fromUtf8("img/colorized_circles/circle16.png")))
        self.circle16.setScaledContents(True)
        self.circle16.setObjectName(_fromUtf8("circle16"))
        self.circle17 = QtGui.QLabel(self.dots_widget)
        self.circle17.setGeometry(QtCore.QRect(241, 55, 31, 31))
        self.circle17.setText(_fromUtf8(""))
        self.circle17.setPixmap(QtGui.QPixmap(_fromUtf8("img/colorized_circles/circle17.png")))
        self.circle17.setScaledContents(True)
        self.circle17.setObjectName(_fromUtf8("circle17"))
        self.circle18 = QtGui.QLabel(self.dots_widget)
        self.circle18.setGeometry(QtCore.QRect(253, 75, 31, 31))
        self.circle18.setText(_fromUtf8(""))
        self.circle18.setPixmap(QtGui.QPixmap(_fromUtf8("img/colorized_circles/circle18.png")))
        self.circle18.setScaledContents(True)
        self.circle18.setObjectName(_fromUtf8("circle18"))
        self.circle19 = QtGui.QLabel(self.dots_widget)
        self.circle19.setGeometry(QtCore.QRect(263, 98, 31, 31))
        self.circle19.setText(_fromUtf8(""))
        self.circle19.setPixmap(QtGui.QPixmap(_fromUtf8("img/colorized_circles/circle19.png")))
        self.circle19.setScaledContents(True)
        self.circle19.setObjectName(_fromUtf8("circle19"))
        self.circle20 = QtGui.QLabel(self.dots_widget)
        self.circle20.setGeometry(QtCore.QRect(269, 121, 31, 31))
        self.circle20.setText(_fromUtf8(""))
        self.circle20.setPixmap(QtGui.QPixmap(_fromUtf8("img/colorized_circles/circle20.png")))
        self.circle20.setScaledContents(True)
        self.circle20.setObjectName(_fromUtf8("circle20"))
        self.circle21 = QtGui.QLabel(self.dots_widget)
        self.circle21.setGeometry(QtCore.QRect(270, 145, 31, 31))
        self.circle21.setText(_fromUtf8(""))
        self.circle21.setPixmap(QtGui.QPixmap(_fromUtf8("img/colorized_circles/circle21.png")))
        self.circle21.setScaledContents(True)
        self.circle21.setObjectName(_fromUtf8("circle21"))
        self.circle22 = QtGui.QLabel(self.dots_widget)
        self.circle22.setGeometry(QtCore.QRect(266, 169, 31, 31))
        self.circle22.setText(_fromUtf8(""))
        self.circle22.setPixmap(QtGui.QPixmap(_fromUtf8("img/colorized_circles/circle22.png")))
        self.circle22.setScaledContents(True)
        self.circle22.setObjectName(_fromUtf8("circle22"))
        self.circle23 = QtGui.QLabel(self.dots_widget)
        self.circle23.setGeometry(QtCore.QRect(257, 191, 31, 31))
        self.circle23.setText(_fromUtf8(""))
        self.circle23.setPixmap(QtGui.QPixmap(_fromUtf8("img/colorized_circles/circle23.png")))
        self.circle23.setScaledContents(True)
        self.circle23.setObjectName(_fromUtf8("circle23"))
        self.pintop = QtGui.QLabel(rpm_widget)
        self.pintop.setGeometry(QtCore.QRect(130, 110, 41, 41))
        self.pintop.setStyleSheet(_fromUtf8("background: none;"))
        self.pintop.setFrameShape(QtGui.QFrame.NoFrame)
        self.pintop.setText(_fromUtf8(""))
        self.pintop.setPixmap(QtGui.QPixmap(_fromUtf8("img/pintop.png")))
        self.pintop.setScaledContents(True)
        self.pintop.setObjectName(_fromUtf8("pintop"))

        self.retranslateUi(rpm_widget)
        QtCore.QMetaObject.connectSlotsByName(rpm_widget)

    def retranslateUi(self, rpm_widget):
        rpm_widget.setWindowTitle(_translate("rpm_widget", "Form", None))
        self.rpmCaption.setText(_translate("rpm_widget", "RPM * 1000/min", None))

