# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'window.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(960, 624)
        MainWindow.setStyleSheet("background-color: qradialgradient(spread:pad, cx:0.5, cy:0.5, radius:0.5, fx:0.5, fy:0.5, stop:0 rgba(255, 255, 255, 255), stop:1 rgba(191, 191, 191, 255))")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("b")
        self.centralwidget.setObjectName("centralwidget")
        self.rpm_widget = QtWidgets.QWidget(self.centralwidget)
        self.rpm_widget.setGeometry(QtCore.QRect(330, 100, 301, 301))
        self.rpm_widget.setStyleSheet("background-color: none;")
        self.rpm_widget.setObjectName("rpm_widget")
        self.progressBar = QtWidgets.QProgressBar(self.centralwidget)
        self.progressBar.setGeometry(QtCore.QRect(820, 0, 111, 71))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.progressBar.setFont(font)
        self.progressBar.setStyleSheet("")
        self.progressBar.setMaximum(255)
        self.progressBar.setProperty("value", 60)
        self.progressBar.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.progressBar.setTextVisible(True)
        self.progressBar.setOrientation(QtCore.Qt.Horizontal)
        self.progressBar.setInvertedAppearance(True)
        self.progressBar.setTextDirection(QtWidgets.QProgressBar.TopToBottom)
        self.progressBar.setObjectName("progressBar")
        self.label_23 = QtWidgets.QLabel(self.centralwidget)
        self.label_23.setGeometry(QtCore.QRect(720, 20, 91, 41))
        font = QtGui.QFont()
        font.setFamily("Lato")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_23.setFont(font)
        self.label_23.setStyleSheet("background:none;")
        self.label_23.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_23.setObjectName("label_23")
        self.btnStart = QtWidgets.QPushButton(self.centralwidget)
        self.btnStart.setGeometry(QtCore.QRect(10, 50, 141, 41))
        font = QtGui.QFont()
        font.setFamily("Lato")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.btnStart.setFont(font)
        self.btnStart.setStyleSheet("background-color: qconicalgradient(cx:0.5, cy:0.5, angle:0, stop:0.113636 rgba(185, 173, 80, 255), stop:0.16 rgba(136, 106, 22, 255), stop:0.225 rgba(166, 140, 41, 255), stop:0.285 rgba(204, 181, 74, 255), stop:0.482955 rgba(245, 236, 112, 255), stop:0.579545 rgba(187, 156, 51, 255), stop:0.635 rgba(168, 142, 42, 255), stop:0.695 rgba(202, 174, 68, 255), stop:0.75 rgba(218, 202, 86, 255), stop:0.815 rgba(208, 187, 73, 255), stop:0.886364 rgba(137, 108, 26, 255), stop:0.971591 rgba(187, 156, 51, 255), stop:1 rgba(209, 190, 76, 255));\n"
"color: rgb(255, 255, 255);")
        self.btnStart.setObjectName("btnStart")
        self.label_24 = QtWidgets.QLabel(self.centralwidget)
        self.label_24.setGeometry(QtCore.QRect(670, 90, 231, 31))
        font = QtGui.QFont()
        font.setFamily("Lato")
        font.setPointSize(16)
        self.label_24.setFont(font)
        self.label_24.setStyleSheet("background:none;")
        self.label_24.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_24.setObjectName("label_24")
        self.timeEdit = QtWidgets.QTimeEdit(self.centralwidget)
        self.timeEdit.setGeometry(QtCore.QRect(670, 120, 261, 71))
        font = QtGui.QFont()
        font.setFamily("Lato")
        font.setPointSize(48)
        self.timeEdit.setFont(font)
        self.timeEdit.setStyleSheet("")
        self.timeEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.timeEdit.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.timeEdit.setAccelerated(False)
        self.timeEdit.setKeyboardTracking(False)
        self.timeEdit.setTime(QtCore.QTime(0, 0, 0))
        self.timeEdit.setMaximumDateTime(QtCore.QDateTime(QtCore.QDate(2000, 1, 1), QtCore.QTime(23, 59, 59)))
        self.timeEdit.setCurrentSection(QtWidgets.QDateTimeEdit.HourSection)
        self.timeEdit.setObjectName("timeEdit")
        self.btnStopwatch = QtWidgets.QPushButton(self.centralwidget)
        self.btnStopwatch.setGeometry(QtCore.QRect(670, 200, 121, 41))
        font = QtGui.QFont()
        font.setFamily("Lato")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.btnStopwatch.setFont(font)
        self.btnStopwatch.setStyleSheet("background-color: qconicalgradient(cx:0.5, cy:0.5, angle:0, stop:0.113636 rgba(185, 173, 80, 255), stop:0.16 rgba(136, 106, 22, 255), stop:0.225 rgba(166, 140, 41, 255), stop:0.285 rgba(204, 181, 74, 255), stop:0.482955 rgba(245, 236, 112, 255), stop:0.579545 rgba(187, 156, 51, 255), stop:0.635 rgba(168, 142, 42, 255), stop:0.695 rgba(202, 174, 68, 255), stop:0.75 rgba(218, 202, 86, 255), stop:0.815 rgba(208, 187, 73, 255), stop:0.886364 rgba(137, 108, 26, 255), stop:0.971591 rgba(187, 156, 51, 255), stop:1 rgba(209, 190, 76, 255));\n"
"color: rgb(255, 255, 255);")
        self.btnStopwatch.setObjectName("btnStopwatch")
        self.btnNewLap = QtWidgets.QPushButton(self.centralwidget)
        self.btnNewLap.setGeometry(QtCore.QRect(810, 200, 121, 41))
        font = QtGui.QFont()
        font.setFamily("Lato")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.btnNewLap.setFont(font)
        self.btnNewLap.setObjectName("btnNewLap")
        self.listView = QtWidgets.QListView(self.centralwidget)
        self.listView.setGeometry(QtCore.QRect(670, 250, 256, 261))
        self.listView.setObjectName("listView")
        self.voltageBar = QtWidgets.QProgressBar(self.centralwidget)
        self.voltageBar.setGeometry(QtCore.QRect(150, 410, 151, 51))
        font = QtGui.QFont()
        font.setFamily("Lato")
        font.setPointSize(20)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        self.voltageBar.setFont(font)
        self.voltageBar.setStyleSheet("QProgressBar::chunk { background: green; margin:0.5px; width: 10px;}\n"
"QProgressBar {color: white; padding: 2px;}")
        self.voltageBar.setMaximum(255)
        self.voltageBar.setProperty("value", 71)
        self.voltageBar.setAlignment(QtCore.Qt.AlignCenter)
        self.voltageBar.setObjectName("voltageBar")
        self.label_25 = QtWidgets.QLabel(self.centralwidget)
        self.label_25.setGeometry(QtCore.QRect(10, 410, 131, 51))
        font = QtGui.QFont()
        font.setFamily("Lato")
        font.setPointSize(14)
        self.label_25.setFont(font)
        self.label_25.setStyleSheet("background: none;")
        self.label_25.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_25.setObjectName("label_25")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(0, 100, 281, 281))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.tempNumber = QtWidgets.QLabel(self.frame)
        self.tempNumber.setGeometry(QtCore.QRect(90, 20, 181, 201))
        font = QtGui.QFont()
        font.setPointSize(48)
        self.tempNumber.setFont(font)
        self.tempNumber.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.tempNumber.setStyleSheet("background: none;")
        self.tempNumber.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.tempNumber.setObjectName("tempNumber")
        self.label_21 = QtWidgets.QLabel(self.frame)
        self.label_21.setGeometry(QtCore.QRect(20, 210, 251, 81))
        font = QtGui.QFont()
        font.setFamily("Lucida Console")
        font.setPointSize(26)
        self.label_21.setFont(font)
        self.label_21.setStyleSheet("background-color: none;")
        self.label_21.setObjectName("label_21")
        self.label_20 = QtWidgets.QLabel(self.frame)
        self.label_20.setGeometry(QtCore.QRect(10, 20, 31, 201))
        self.label_20.setAutoFillBackground(False)
        self.label_20.setStyleSheet("background: none;")
        self.label_20.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_20.setObjectName("label_20")
        self.tempBar = QtWidgets.QGraphicsView(self.frame)
        self.tempBar.setGeometry(QtCore.QRect(50, 10, 41, 201))
        self.tempBar.setStyleSheet("background: transparent;")
        self.tempBar.setObjectName("tempBar")
        self.currentBar = QtWidgets.QProgressBar(self.centralwidget)
        self.currentBar.setGeometry(QtCore.QRect(150, 470, 151, 61))
        font = QtGui.QFont()
        font.setFamily("Lato")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.currentBar.setFont(font)
        self.currentBar.setStyleSheet("QProgressBar::chunk { background: yellow; margin:0.5px; width: 10px;}\n"
"QProgressBar {color:black; padding: 2px;}")
        self.currentBar.setMaximum(255)
        self.currentBar.setProperty("value", 24)
        self.currentBar.setAlignment(QtCore.Qt.AlignCenter)
        self.currentBar.setObjectName("currentBar")
        self.label_26 = QtWidgets.QLabel(self.centralwidget)
        self.label_26.setGeometry(QtCore.QRect(10, 470, 131, 51))
        font = QtGui.QFont()
        font.setFamily("Lato")
        font.setPointSize(14)
        self.label_26.setFont(font)
        self.label_26.setStyleSheet("background: none;")
        self.label_26.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_26.setObjectName("label_26")
        self.btnConnect = QtWidgets.QPushButton(self.centralwidget)
        self.btnConnect.setGeometry(QtCore.QRect(10, 0, 141, 41))
        font = QtGui.QFont()
        font.setFamily("Lato")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.btnConnect.setFont(font)
        self.btnConnect.setStyleSheet("background-color: qconicalgradient(cx:0.5, cy:0.5, angle:0, stop:0.113636 rgba(185, 173, 80, 255), stop:0.16 rgba(136, 106, 22, 255), stop:0.225 rgba(166, 140, 41, 255), stop:0.285 rgba(204, 181, 74, 255), stop:0.482955 rgba(245, 236, 112, 255), stop:0.579545 rgba(187, 156, 51, 255), stop:0.635 rgba(168, 142, 42, 255), stop:0.695 rgba(202, 174, 68, 255), stop:0.75 rgba(218, 202, 86, 255), stop:0.815 rgba(208, 187, 73, 255), stop:0.886364 rgba(137, 108, 26, 255), stop:0.971591 rgba(187, 156, 51, 255), stop:1 rgba(209, 190, 76, 255));\n"
"color: rgb(255, 255, 255);")
        self.btnConnect.setObjectName("btnConnect")
        self.label_27 = QtWidgets.QLabel(self.centralwidget)
        self.label_27.setGeometry(QtCore.QRect(170, 0, 81, 31))
        font = QtGui.QFont()
        font.setFamily("Lato")
        font.setPointSize(16)
        self.label_27.setFont(font)
        self.label_27.setStyleSheet("background: none;")
        self.label_27.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_27.setObjectName("label_27")
        self.labelStatus = QtWidgets.QLabel(self.centralwidget)
        self.labelStatus.setGeometry(QtCore.QRect(260, 0, 141, 31))
        font = QtGui.QFont()
        font.setFamily("Lato")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.labelStatus.setFont(font)
        self.labelStatus.setStyleSheet("background: none;\n"
"color: rgb(255, 0, 0);")
        self.labelStatus.setObjectName("labelStatus")
        self.framesLabel = QtWidgets.QLabel(self.centralwidget)
        self.framesLabel.setGeometry(QtCore.QRect(230, 40, 451, 51))
        self.framesLabel.setObjectName("framesLabel")
        self.dial = QtWidgets.QDial(self.centralwidget)
        self.dial.setGeometry(QtCore.QRect(380, 420, 181, 111))
        self.dial.setMaximum(255)
        self.dial.setSingleStep(1)
        self.dial.setObjectName("dial")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(540, 430, 75, 23))
        self.pushButton.setObjectName("pushButton")
        self.frame.raise_()
        self.rpm_widget.raise_()
        self.progressBar.raise_()
        self.label_23.raise_()
        self.btnStart.raise_()
        self.label_24.raise_()
        self.timeEdit.raise_()
        self.btnStopwatch.raise_()
        self.btnNewLap.raise_()
        self.listView.raise_()
        self.voltageBar.raise_()
        self.label_25.raise_()
        self.currentBar.raise_()
        self.label_26.raise_()
        self.btnConnect.raise_()
        self.label_27.raise_()
        self.labelStatus.raise_()
        self.framesLabel.raise_()
        self.dial.raise_()
        self.pushButton.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 960, 27))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_23.setText(_translate("MainWindow", "Battery:"))
        self.btnStart.setText(_translate("MainWindow", "START"))
        self.label_24.setText(_translate("MainWindow", "Laptime"))
        self.timeEdit.setDisplayFormat(_translate("MainWindow", "HH:mm:ss"))
        self.btnStopwatch.setText(_translate("MainWindow", "Start"))
        self.btnNewLap.setText(_translate("MainWindow", "New lap"))
        self.voltageBar.setFormat(_translate("MainWindow", "%v V"))
        self.label_25.setText(_translate("MainWindow", "Battery Voltage"))
        self.tempNumber.setText(_translate("MainWindow", "<html><head/><body><p>0 <span style=\" vertical-align:super;\">o</span>C</p></body></html>"))
        self.label_21.setText(_translate("MainWindow", "Engine temp."))
        self.label_20.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:9pt;\">250<br/><br/><br/>187.5<br/><br/><br/>125<br/><br/><br/>62.5<br/><br/><br/>0</span></p></body></html>"))
        self.currentBar.setFormat(_translate("MainWindow", "%v A"))
        self.label_26.setText(_translate("MainWindow", "Battery Current"))
        self.btnConnect.setText(_translate("MainWindow", "Connect"))
        self.label_27.setText(_translate("MainWindow", "Status: "))
        self.labelStatus.setText(_translate("MainWindow", "Not connected"))
        self.framesLabel.setText(_translate("MainWindow", "TextLabel"))
        self.pushButton.setText(_translate("MainWindow", "PushButton"))

