# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'window.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(960, 624)
        MainWindow.setStyleSheet(_fromUtf8("background-color: qradialgradient(spread:pad, cx:0.5, cy:0.5, radius:0.5, fx:0.5, fy:0.5, stop:0 rgba(255, 255, 255, 255), stop:1 rgba(191, 191, 191, 255))"))
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setStyleSheet(_fromUtf8("b"))
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.rpm_widget = QtGui.QWidget(self.centralwidget)
        self.rpm_widget.setGeometry(QtCore.QRect(330, 100, 301, 301))
        self.rpm_widget.setStyleSheet(_fromUtf8("background-color: none;"))
        self.rpm_widget.setObjectName(_fromUtf8("rpm_widget"))
        self.rpmCaption = QtGui.QLabel(self.rpm_widget)
        self.rpmCaption.setGeometry(QtCore.QRect(50, 238, 191, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Levenim MT"))
        font.setPointSize(18)
        self.rpmCaption.setFont(font)
        self.rpmCaption.setStyleSheet(_fromUtf8("color: white; background:none;"))
        self.rpmCaption.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.rpmCaption.setObjectName(_fromUtf8("rpmCaption"))
        self.rpmNumber = QtGui.QLCDNumber(self.rpm_widget)
        self.rpmNumber.setGeometry(QtCore.QRect(74, 173, 151, 61))
        self.rpmNumber.setStyleSheet(_fromUtf8("color: yellow;\n"
"background-color: rgba(255, 255, 255, 20)"))
        self.rpmNumber.setFrameShape(QtGui.QFrame.NoFrame)
        self.rpmNumber.setDigitCount(5)
        self.rpmNumber.setObjectName(_fromUtf8("rpmNumber"))
        self.black_circle = QtGui.QLabel(self.rpm_widget)
        self.black_circle.setGeometry(QtCore.QRect(0, 0, 301, 301))
        self.black_circle.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.black_circle.setStyleSheet(_fromUtf8("background-color: none;"))
        self.black_circle.setFrameShape(QtGui.QFrame.Box)
        self.black_circle.setFrameShadow(QtGui.QFrame.Sunken)
        self.black_circle.setText(_fromUtf8(""))
        self.black_circle.setPixmap(QtGui.QPixmap(_fromUtf8("img/blackcircle.png")))
        self.black_circle.setScaledContents(True)
        self.black_circle.setObjectName(_fromUtf8("black_circle"))
        self.pintop = QtGui.QLabel(self.rpm_widget)
        self.pintop.setGeometry(QtCore.QRect(130, 130, 41, 41))
        self.pintop.setStyleSheet(_fromUtf8("background: none;"))
        self.pintop.setFrameShape(QtGui.QFrame.NoFrame)
        self.pintop.setText(_fromUtf8(""))
        self.pintop.setPixmap(QtGui.QPixmap(_fromUtf8("img/pintop.png")))
        self.pintop.setScaledContents(True)
        self.pintop.setObjectName(_fromUtf8("pintop"))
        self.dots_widget = QtGui.QWidget(self.rpm_widget)
        self.dots_widget.setEnabled(True)
        self.dots_widget.setGeometry(QtCore.QRect(0, 0, 301, 301))
        self.dots_widget.setObjectName(_fromUtf8("dots_widget"))
        self.circle1 = QtGui.QLabel(self.dots_widget)
        self.circle1.setGeometry(QtCore.QRect(14, 195, 31, 31))
        self.circle1.setText(_fromUtf8(""))
        self.circle1.setPixmap(QtGui.QPixmap(_fromUtf8("img/colorized_circles/circle1.png")))
        self.circle1.setScaledContents(True)
        self.circle1.setObjectName(_fromUtf8("circle1"))
        self.circle2 = QtGui.QLabel(self.dots_widget)
        self.circle2.setGeometry(QtCore.QRect(7, 172, 31, 31))
        self.circle2.setText(_fromUtf8(""))
        self.circle2.setPixmap(QtGui.QPixmap(_fromUtf8("img/colorized_circles/circle2.png")))
        self.circle2.setScaledContents(True)
        self.circle2.setObjectName(_fromUtf8("circle2"))
        self.circle3 = QtGui.QLabel(self.dots_widget)
        self.circle3.setGeometry(QtCore.QRect(1, 148, 31, 31))
        self.circle3.setText(_fromUtf8(""))
        self.circle3.setPixmap(QtGui.QPixmap(_fromUtf8("img/colorized_circles/circle3.png")))
        self.circle3.setScaledContents(True)
        self.circle3.setObjectName(_fromUtf8("circle3"))
        self.circle4 = QtGui.QLabel(self.dots_widget)
        self.circle4.setGeometry(QtCore.QRect(2, 124, 31, 31))
        self.circle4.setText(_fromUtf8(""))
        self.circle4.setPixmap(QtGui.QPixmap(_fromUtf8("img/colorized_circles/circle4.png")))
        self.circle4.setScaledContents(True)
        self.circle4.setObjectName(_fromUtf8("circle4"))
        self.circle5 = QtGui.QLabel(self.dots_widget)
        self.circle5.setGeometry(QtCore.QRect(8, 99, 31, 31))
        self.circle5.setText(_fromUtf8(""))
        self.circle5.setPixmap(QtGui.QPixmap(_fromUtf8("img/colorized_circles/circle5.png")))
        self.circle5.setScaledContents(True)
        self.circle5.setObjectName(_fromUtf8("circle5"))
        self.circle6 = QtGui.QLabel(self.dots_widget)
        self.circle6.setGeometry(QtCore.QRect(18, 75, 31, 31))
        self.circle6.setText(_fromUtf8(""))
        self.circle6.setPixmap(QtGui.QPixmap(_fromUtf8("img/colorized_circles/circle6.png")))
        self.circle6.setScaledContents(True)
        self.circle6.setObjectName(_fromUtf8("circle6"))
        self.circle7 = QtGui.QLabel(self.dots_widget)
        self.circle7.setGeometry(QtCore.QRect(31, 54, 31, 31))
        self.circle7.setText(_fromUtf8(""))
        self.circle7.setPixmap(QtGui.QPixmap(_fromUtf8("img/colorized_circles/circle7.png")))
        self.circle7.setScaledContents(True)
        self.circle7.setObjectName(_fromUtf8("circle7"))
        self.circle8 = QtGui.QLabel(self.dots_widget)
        self.circle8.setGeometry(QtCore.QRect(48, 36, 31, 31))
        self.circle8.setText(_fromUtf8(""))
        self.circle8.setPixmap(QtGui.QPixmap(_fromUtf8("img/colorized_circles/circle8.png")))
        self.circle8.setScaledContents(True)
        self.circle8.setObjectName(_fromUtf8("circle8"))
        self.circle9 = QtGui.QLabel(self.dots_widget)
        self.circle9.setGeometry(QtCore.QRect(68, 21, 31, 31))
        self.circle9.setText(_fromUtf8(""))
        self.circle9.setPixmap(QtGui.QPixmap(_fromUtf8("img/colorized_circles/circle9.png")))
        self.circle9.setScaledContents(True)
        self.circle9.setObjectName(_fromUtf8("circle9"))
        self.circle10 = QtGui.QLabel(self.dots_widget)
        self.circle10.setGeometry(QtCore.QRect(89, 11, 31, 31))
        self.circle10.setText(_fromUtf8(""))
        self.circle10.setPixmap(QtGui.QPixmap(_fromUtf8("img/colorized_circles/circle10.png")))
        self.circle10.setScaledContents(True)
        self.circle10.setObjectName(_fromUtf8("circle10"))
        self.circle11 = QtGui.QLabel(self.dots_widget)
        self.circle11.setEnabled(True)
        self.circle11.setGeometry(QtCore.QRect(112, 4, 31, 31))
        self.circle11.setText(_fromUtf8(""))
        self.circle11.setPixmap(QtGui.QPixmap(_fromUtf8("img/colorized_circles/circle11.png")))
        self.circle11.setScaledContents(True)
        self.circle11.setObjectName(_fromUtf8("circle11"))
        self.circle12 = QtGui.QLabel(self.dots_widget)
        self.circle12.setGeometry(QtCore.QRect(136, 1, 31, 31))
        self.circle12.setText(_fromUtf8(""))
        self.circle12.setPixmap(QtGui.QPixmap(_fromUtf8("img/colorized_circles/circle12.png")))
        self.circle12.setScaledContents(True)
        self.circle12.setObjectName(_fromUtf8("circle12"))
        self.circle13 = QtGui.QLabel(self.dots_widget)
        self.circle13.setGeometry(QtCore.QRect(159, 5, 31, 31))
        self.circle13.setText(_fromUtf8(""))
        self.circle13.setPixmap(QtGui.QPixmap(_fromUtf8("img/colorized_circles/circle13.png")))
        self.circle13.setScaledContents(True)
        self.circle13.setObjectName(_fromUtf8("circle13"))
        self.circle14 = QtGui.QLabel(self.dots_widget)
        self.circle14.setGeometry(QtCore.QRect(182, 11, 31, 31))
        self.circle14.setText(_fromUtf8(""))
        self.circle14.setPixmap(QtGui.QPixmap(_fromUtf8("img/colorized_circles/circle14.png")))
        self.circle14.setScaledContents(True)
        self.circle14.setObjectName(_fromUtf8("circle14"))
        self.circle15 = QtGui.QLabel(self.dots_widget)
        self.circle15.setGeometry(QtCore.QRect(205, 21, 31, 31))
        self.circle15.setText(_fromUtf8(""))
        self.circle15.setPixmap(QtGui.QPixmap(_fromUtf8("img/colorized_circles/circle15.png")))
        self.circle15.setScaledContents(True)
        self.circle15.setObjectName(_fromUtf8("circle15"))
        self.circle16 = QtGui.QLabel(self.dots_widget)
        self.circle16.setGeometry(QtCore.QRect(224, 37, 31, 31))
        self.circle16.setText(_fromUtf8(""))
        self.circle16.setPixmap(QtGui.QPixmap(_fromUtf8("img/colorized_circles/circle16.png")))
        self.circle16.setScaledContents(True)
        self.circle16.setObjectName(_fromUtf8("circle16"))
        self.circle17 = QtGui.QLabel(self.dots_widget)
        self.circle17.setGeometry(QtCore.QRect(241, 55, 31, 31))
        self.circle17.setText(_fromUtf8(""))
        self.circle17.setPixmap(QtGui.QPixmap(_fromUtf8("img/colorized_circles/circle17.png")))
        self.circle17.setScaledContents(True)
        self.circle17.setObjectName(_fromUtf8("circle17"))
        self.circle18 = QtGui.QLabel(self.dots_widget)
        self.circle18.setGeometry(QtCore.QRect(253, 75, 31, 31))
        self.circle18.setText(_fromUtf8(""))
        self.circle18.setPixmap(QtGui.QPixmap(_fromUtf8("img/colorized_circles/circle18.png")))
        self.circle18.setScaledContents(True)
        self.circle18.setObjectName(_fromUtf8("circle18"))
        self.circle19 = QtGui.QLabel(self.dots_widget)
        self.circle19.setGeometry(QtCore.QRect(263, 98, 31, 31))
        self.circle19.setText(_fromUtf8(""))
        self.circle19.setPixmap(QtGui.QPixmap(_fromUtf8("img/colorized_circles/circle19.png")))
        self.circle19.setScaledContents(True)
        self.circle19.setObjectName(_fromUtf8("circle19"))
        self.circle20 = QtGui.QLabel(self.dots_widget)
        self.circle20.setGeometry(QtCore.QRect(269, 121, 31, 31))
        self.circle20.setText(_fromUtf8(""))
        self.circle20.setPixmap(QtGui.QPixmap(_fromUtf8("img/colorized_circles/circle20.png")))
        self.circle20.setScaledContents(True)
        self.circle20.setObjectName(_fromUtf8("circle20"))
        self.circle21 = QtGui.QLabel(self.dots_widget)
        self.circle21.setGeometry(QtCore.QRect(270, 145, 31, 31))
        self.circle21.setText(_fromUtf8(""))
        self.circle21.setPixmap(QtGui.QPixmap(_fromUtf8("img/colorized_circles/circle21.png")))
        self.circle21.setScaledContents(True)
        self.circle21.setObjectName(_fromUtf8("circle21"))
        self.circle22 = QtGui.QLabel(self.dots_widget)
        self.circle22.setGeometry(QtCore.QRect(266, 169, 31, 31))
        self.circle22.setText(_fromUtf8(""))
        self.circle22.setPixmap(QtGui.QPixmap(_fromUtf8("img/colorized_circles/circle22.png")))
        self.circle22.setScaledContents(True)
        self.circle22.setObjectName(_fromUtf8("circle22"))
        self.circle23 = QtGui.QLabel(self.dots_widget)
        self.circle23.setGeometry(QtCore.QRect(257, 191, 31, 31))
        self.circle23.setText(_fromUtf8(""))
        self.circle23.setPixmap(QtGui.QPixmap(_fromUtf8("img/colorized_circles/circle23.png")))
        self.circle23.setScaledContents(True)
        self.circle23.setObjectName(_fromUtf8("circle23"))
        self.graphicsView = QtGui.QGraphicsView(self.rpm_widget)
        self.graphicsView.setGeometry(QtCore.QRect(0, 0, 301, 301))
        self.graphicsView.setStyleSheet(_fromUtf8("background: transparent; "))
        self.graphicsView.setObjectName(_fromUtf8("graphicsView"))
        self.black_circle.raise_()
        self.rpmNumber.raise_()
        self.pintop.raise_()
        self.dots_widget.raise_()
        self.rpmCaption.raise_()
        self.graphicsView.raise_()
        self.progressBar = QtGui.QProgressBar(self.centralwidget)
        self.progressBar.setGeometry(QtCore.QRect(820, 0, 111, 71))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.progressBar.setFont(font)
        self.progressBar.setStyleSheet(_fromUtf8(""))
        self.progressBar.setMaximum(255)
        self.progressBar.setProperty("value", 60)
        self.progressBar.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.progressBar.setTextVisible(True)
        self.progressBar.setOrientation(QtCore.Qt.Horizontal)
        self.progressBar.setInvertedAppearance(True)
        self.progressBar.setTextDirection(QtGui.QProgressBar.TopToBottom)
        self.progressBar.setObjectName(_fromUtf8("progressBar"))
        self.label_23 = QtGui.QLabel(self.centralwidget)
        self.label_23.setGeometry(QtCore.QRect(720, 20, 91, 41))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Lato"))
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_23.setFont(font)
        self.label_23.setStyleSheet(_fromUtf8("background:none;"))
        self.label_23.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_23.setObjectName(_fromUtf8("label_23"))
        self.btnStart = QtGui.QPushButton(self.centralwidget)
        self.btnStart.setGeometry(QtCore.QRect(10, 50, 141, 41))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Lato"))
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.btnStart.setFont(font)
        self.btnStart.setStyleSheet(_fromUtf8("background-color: qconicalgradient(cx:0.5, cy:0.5, angle:0, stop:0.113636 rgba(185, 173, 80, 255), stop:0.16 rgba(136, 106, 22, 255), stop:0.225 rgba(166, 140, 41, 255), stop:0.285 rgba(204, 181, 74, 255), stop:0.482955 rgba(245, 236, 112, 255), stop:0.579545 rgba(187, 156, 51, 255), stop:0.635 rgba(168, 142, 42, 255), stop:0.695 rgba(202, 174, 68, 255), stop:0.75 rgba(218, 202, 86, 255), stop:0.815 rgba(208, 187, 73, 255), stop:0.886364 rgba(137, 108, 26, 255), stop:0.971591 rgba(187, 156, 51, 255), stop:1 rgba(209, 190, 76, 255));\n"
"color: rgb(255, 255, 255);"))
        self.btnStart.setObjectName(_fromUtf8("btnStart"))
        self.label_24 = QtGui.QLabel(self.centralwidget)
        self.label_24.setGeometry(QtCore.QRect(670, 90, 231, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Lato"))
        font.setPointSize(16)
        self.label_24.setFont(font)
        self.label_24.setStyleSheet(_fromUtf8("background:none;"))
        self.label_24.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_24.setObjectName(_fromUtf8("label_24"))
        self.timeEdit = QtGui.QTimeEdit(self.centralwidget)
        self.timeEdit.setGeometry(QtCore.QRect(670, 120, 261, 71))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Lato"))
        font.setPointSize(48)
        self.timeEdit.setFont(font)
        self.timeEdit.setStyleSheet(_fromUtf8(""))
        self.timeEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.timeEdit.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.timeEdit.setAccelerated(False)
        self.timeEdit.setKeyboardTracking(False)
        self.timeEdit.setTime(QtCore.QTime(0, 0, 0))
        self.timeEdit.setMaximumDateTime(QtCore.QDateTime(QtCore.QDate(2000, 1, 1), QtCore.QTime(23, 59, 59)))
        self.timeEdit.setCurrentSection(QtGui.QDateTimeEdit.HourSection)
        self.timeEdit.setObjectName(_fromUtf8("timeEdit"))
        self.btnStopwatch = QtGui.QPushButton(self.centralwidget)
        self.btnStopwatch.setGeometry(QtCore.QRect(670, 200, 121, 41))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Lato"))
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.btnStopwatch.setFont(font)
        self.btnStopwatch.setStyleSheet(_fromUtf8("background-color: qconicalgradient(cx:0.5, cy:0.5, angle:0, stop:0.113636 rgba(185, 173, 80, 255), stop:0.16 rgba(136, 106, 22, 255), stop:0.225 rgba(166, 140, 41, 255), stop:0.285 rgba(204, 181, 74, 255), stop:0.482955 rgba(245, 236, 112, 255), stop:0.579545 rgba(187, 156, 51, 255), stop:0.635 rgba(168, 142, 42, 255), stop:0.695 rgba(202, 174, 68, 255), stop:0.75 rgba(218, 202, 86, 255), stop:0.815 rgba(208, 187, 73, 255), stop:0.886364 rgba(137, 108, 26, 255), stop:0.971591 rgba(187, 156, 51, 255), stop:1 rgba(209, 190, 76, 255));\n"
"color: rgb(255, 255, 255);"))
        self.btnStopwatch.setObjectName(_fromUtf8("btnStopwatch"))
        self.btnNewLap = QtGui.QPushButton(self.centralwidget)
        self.btnNewLap.setGeometry(QtCore.QRect(810, 200, 121, 41))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Lato"))
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.btnNewLap.setFont(font)
        self.btnNewLap.setObjectName(_fromUtf8("btnNewLap"))
        self.listView = QtGui.QListView(self.centralwidget)
        self.listView.setGeometry(QtCore.QRect(670, 250, 256, 261))
        self.listView.setObjectName(_fromUtf8("listView"))
        self.voltageBar = QtGui.QProgressBar(self.centralwidget)
        self.voltageBar.setGeometry(QtCore.QRect(150, 410, 151, 51))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Lato"))
        font.setPointSize(20)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        self.voltageBar.setFont(font)
        self.voltageBar.setStyleSheet(_fromUtf8("QProgressBar::chunk { background: green; margin:0.5px; width: 10px;}\n"
"QProgressBar {color: white; padding: 2px;}"))
        self.voltageBar.setMaximum(255)
        self.voltageBar.setProperty("value", 71)
        self.voltageBar.setAlignment(QtCore.Qt.AlignCenter)
        self.voltageBar.setObjectName(_fromUtf8("voltageBar"))
        self.label_25 = QtGui.QLabel(self.centralwidget)
        self.label_25.setGeometry(QtCore.QRect(10, 410, 131, 51))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Lato"))
        font.setPointSize(14)
        self.label_25.setFont(font)
        self.label_25.setStyleSheet(_fromUtf8("background: none;"))
        self.label_25.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_25.setObjectName(_fromUtf8("label_25"))
        self.frame = QtGui.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(0, 100, 281, 281))
        self.frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName(_fromUtf8("frame"))
        self.tempNumber = QtGui.QLabel(self.frame)
        self.tempNumber.setGeometry(QtCore.QRect(90, 20, 181, 201))
        font = QtGui.QFont()
        font.setPointSize(48)
        self.tempNumber.setFont(font)
        self.tempNumber.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.tempNumber.setStyleSheet(_fromUtf8("background: none;"))
        self.tempNumber.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.tempNumber.setObjectName(_fromUtf8("tempNumber"))
        self.label_21 = QtGui.QLabel(self.frame)
        self.label_21.setGeometry(QtCore.QRect(20, 210, 251, 81))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Lucida Console"))
        font.setPointSize(26)
        self.label_21.setFont(font)
        self.label_21.setStyleSheet(_fromUtf8("background-color: none;"))
        self.label_21.setObjectName(_fromUtf8("label_21"))
        self.label_20 = QtGui.QLabel(self.frame)
        self.label_20.setGeometry(QtCore.QRect(10, 20, 31, 201))
        self.label_20.setAutoFillBackground(False)
        self.label_20.setStyleSheet(_fromUtf8("background: none;"))
        self.label_20.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_20.setObjectName(_fromUtf8("label_20"))
        self.tempBar = QtGui.QGraphicsView(self.frame)
        self.tempBar.setGeometry(QtCore.QRect(50, 10, 41, 201))
        self.tempBar.setStyleSheet(_fromUtf8("background: transparent;"))
        self.tempBar.setObjectName(_fromUtf8("tempBar"))
        self.currentBar = QtGui.QProgressBar(self.centralwidget)
        self.currentBar.setGeometry(QtCore.QRect(150, 470, 151, 61))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Lato"))
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.currentBar.setFont(font)
        self.currentBar.setStyleSheet(_fromUtf8("QProgressBar::chunk { background: yellow; margin:0.5px; width: 10px;}\n"
"QProgressBar {color:black; padding: 2px;}"))
        self.currentBar.setMaximum(255)
        self.currentBar.setProperty("value", 24)
        self.currentBar.setAlignment(QtCore.Qt.AlignCenter)
        self.currentBar.setObjectName(_fromUtf8("currentBar"))
        self.label_26 = QtGui.QLabel(self.centralwidget)
        self.label_26.setGeometry(QtCore.QRect(10, 470, 131, 51))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Lato"))
        font.setPointSize(14)
        self.label_26.setFont(font)
        self.label_26.setStyleSheet(_fromUtf8("background: none;"))
        self.label_26.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_26.setObjectName(_fromUtf8("label_26"))
        self.btnConnect = QtGui.QPushButton(self.centralwidget)
        self.btnConnect.setGeometry(QtCore.QRect(10, 0, 141, 41))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Lato"))
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.btnConnect.setFont(font)
        self.btnConnect.setStyleSheet(_fromUtf8("background-color: qconicalgradient(cx:0.5, cy:0.5, angle:0, stop:0.113636 rgba(185, 173, 80, 255), stop:0.16 rgba(136, 106, 22, 255), stop:0.225 rgba(166, 140, 41, 255), stop:0.285 rgba(204, 181, 74, 255), stop:0.482955 rgba(245, 236, 112, 255), stop:0.579545 rgba(187, 156, 51, 255), stop:0.635 rgba(168, 142, 42, 255), stop:0.695 rgba(202, 174, 68, 255), stop:0.75 rgba(218, 202, 86, 255), stop:0.815 rgba(208, 187, 73, 255), stop:0.886364 rgba(137, 108, 26, 255), stop:0.971591 rgba(187, 156, 51, 255), stop:1 rgba(209, 190, 76, 255));\n"
"color: rgb(255, 255, 255);"))
        self.btnConnect.setObjectName(_fromUtf8("btnConnect"))
        self.label_27 = QtGui.QLabel(self.centralwidget)
        self.label_27.setGeometry(QtCore.QRect(170, 0, 81, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Lato"))
        font.setPointSize(16)
        self.label_27.setFont(font)
        self.label_27.setStyleSheet(_fromUtf8("background: none;"))
        self.label_27.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_27.setObjectName(_fromUtf8("label_27"))
        self.labelStatus = QtGui.QLabel(self.centralwidget)
        self.labelStatus.setGeometry(QtCore.QRect(260, 0, 141, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Lato"))
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.labelStatus.setFont(font)
        self.labelStatus.setStyleSheet(_fromUtf8("background: none;\n"
"color: rgb(255, 0, 0);"))
        self.labelStatus.setObjectName(_fromUtf8("labelStatus"))
        self.framesLabel = QtGui.QLabel(self.centralwidget)
        self.framesLabel.setGeometry(QtCore.QRect(230, 40, 451, 51))
        self.framesLabel.setObjectName(_fromUtf8("framesLabel"))
        self.dial = QtGui.QDial(self.centralwidget)
        self.dial.setGeometry(QtCore.QRect(380, 420, 181, 111))
        self.dial.setMaximum(255)
        self.dial.setSingleStep(1)
        self.dial.setObjectName(_fromUtf8("dial"))
        self.pushButton = QtGui.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(540, 430, 75, 23))
        self.pushButton.setObjectName(_fromUtf8("pushButton"))
        self.frame.raise_()
        self.rpm_widget.raise_()
        self.progressBar.raise_()
        self.label_23.raise_()
        self.btnStart.raise_()
        self.label_24.raise_()
        self.timeEdit.raise_()
        self.btnStopwatch.raise_()
        self.btnNewLap.raise_()
        self.listView.raise_()
        self.voltageBar.raise_()
        self.label_25.raise_()
        self.currentBar.raise_()
        self.label_26.raise_()
        self.btnConnect.raise_()
        self.label_27.raise_()
        self.labelStatus.raise_()
        self.framesLabel.raise_()
        self.dial.raise_()
        self.pushButton.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 960, 21))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow", None))
        self.rpmCaption.setText(_translate("MainWindow", "RPM * 1000/min", None))
        self.label_23.setText(_translate("MainWindow", "Battery:", None))
        self.btnStart.setText(_translate("MainWindow", "START", None))
        self.label_24.setText(_translate("MainWindow", "Laptime", None))
        self.timeEdit.setDisplayFormat(_translate("MainWindow", "HH:mm:ss", None))
        self.btnStopwatch.setText(_translate("MainWindow", "Start", None))
        self.btnNewLap.setText(_translate("MainWindow", "New lap", None))
        self.voltageBar.setFormat(_translate("MainWindow", "%v V", None))
        self.label_25.setText(_translate("MainWindow", "Battery Voltage", None))
        self.tempNumber.setText(_translate("MainWindow", "<html><head/><body><p>0 <span style=\" vertical-align:super;\">o</span>C</p></body></html>", None))
        self.label_21.setText(_translate("MainWindow", "Engine temp.", None))
        self.label_20.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:9pt;\">250<br/><br/><br/>187.5<br/><br/><br/>125<br/><br/><br/>62.5<br/><br/><br/>0</span></p></body></html>", None))
        self.currentBar.setFormat(_translate("MainWindow", "%v A", None))
        self.label_26.setText(_translate("MainWindow", "Battery Current", None))
        self.btnConnect.setText(_translate("MainWindow", "Connect", None))
        self.label_27.setText(_translate("MainWindow", "Status: ", None))
        self.labelStatus.setText(_translate("MainWindow", "Not connected", None))
        self.framesLabel.setText(_translate("MainWindow", "TextLabel", None))
        self.pushButton.setText(_translate("MainWindow", "PushButton", None))

