# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'window.ui'
#
# Created: Tue Sep 19 17:45:04 2017
#      by: PyQt4 UI code generator 4.11.2
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(960, 624)
        MainWindow.setStyleSheet(_fromUtf8("background-color: qradialgradient(spread:pad, cx:0.5, cy:0.5, radius:0.5, fx:0.5, fy:0.5, stop:0 rgba(255, 255, 255, 255), stop:1 rgba(191, 191, 191, 255))"))
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setStyleSheet(_fromUtf8("b"))
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.rpm_widget = QtGui.QWidget(self.centralwidget)
        self.rpm_widget.setGeometry(QtCore.QRect(330, 100, 301, 301))
        self.rpm_widget.setStyleSheet(_fromUtf8("background-color: none;"))
        self.rpm_widget.setObjectName(_fromUtf8("rpm_widget"))
        self.progressBar = QtGui.QProgressBar(self.centralwidget)
        self.progressBar.setGeometry(QtCore.QRect(820, 0, 111, 71))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.progressBar.setFont(font)
        self.progressBar.setStyleSheet(_fromUtf8(""))
        self.progressBar.setMaximum(255)
        self.progressBar.setProperty("value", 60)
        self.progressBar.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.progressBar.setTextVisible(True)
        self.progressBar.setOrientation(QtCore.Qt.Horizontal)
        self.progressBar.setInvertedAppearance(True)
        self.progressBar.setTextDirection(QtGui.QProgressBar.TopToBottom)
        self.progressBar.setObjectName(_fromUtf8("progressBar"))
        self.label_23 = QtGui.QLabel(self.centralwidget)
        self.label_23.setGeometry(QtCore.QRect(720, 20, 91, 41))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Lato"))
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_23.setFont(font)
        self.label_23.setStyleSheet(_fromUtf8("background:none;"))
        self.label_23.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_23.setObjectName(_fromUtf8("label_23"))
        self.btnStart = QtGui.QPushButton(self.centralwidget)
        self.btnStart.setGeometry(QtCore.QRect(10, 50, 141, 41))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Lato"))
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.btnStart.setFont(font)
        self.btnStart.setStyleSheet(_fromUtf8("background-color: qconicalgradient(cx:0.5, cy:0.5, angle:0, stop:0.113636 rgba(185, 173, 80, 255), stop:0.16 rgba(136, 106, 22, 255), stop:0.225 rgba(166, 140, 41, 255), stop:0.285 rgba(204, 181, 74, 255), stop:0.482955 rgba(245, 236, 112, 255), stop:0.579545 rgba(187, 156, 51, 255), stop:0.635 rgba(168, 142, 42, 255), stop:0.695 rgba(202, 174, 68, 255), stop:0.75 rgba(218, 202, 86, 255), stop:0.815 rgba(208, 187, 73, 255), stop:0.886364 rgba(137, 108, 26, 255), stop:0.971591 rgba(187, 156, 51, 255), stop:1 rgba(209, 190, 76, 255));\n"
"color: rgb(255, 255, 255);"))
        self.btnStart.setObjectName(_fromUtf8("btnStart"))
        self.label_24 = QtGui.QLabel(self.centralwidget)
        self.label_24.setGeometry(QtCore.QRect(670, 90, 231, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Lato"))
        font.setPointSize(16)
        self.label_24.setFont(font)
        self.label_24.setStyleSheet(_fromUtf8("background:none;"))
        self.label_24.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_24.setObjectName(_fromUtf8("label_24"))
        self.timeEdit = QtGui.QTimeEdit(self.centralwidget)
        self.timeEdit.setGeometry(QtCore.QRect(670, 120, 261, 71))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Lato"))
        font.setPointSize(48)
        self.timeEdit.setFont(font)
        self.timeEdit.setStyleSheet(_fromUtf8(""))
        self.timeEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.timeEdit.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.timeEdit.setAccelerated(False)
        self.timeEdit.setKeyboardTracking(False)
        self.timeEdit.setTime(QtCore.QTime(0, 0, 0))
        self.timeEdit.setMaximumDateTime(QtCore.QDateTime(QtCore.QDate(2000, 1, 1), QtCore.QTime(23, 59, 59)))
        self.timeEdit.setCurrentSection(QtGui.QDateTimeEdit.HourSection)
        self.timeEdit.setObjectName(_fromUtf8("timeEdit"))
        self.btnStopwatch = QtGui.QPushButton(self.centralwidget)
        self.btnStopwatch.setGeometry(QtCore.QRect(670, 200, 121, 41))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Lato"))
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.btnStopwatch.setFont(font)
        self.btnStopwatch.setStyleSheet(_fromUtf8("background-color: qconicalgradient(cx:0.5, cy:0.5, angle:0, stop:0.113636 rgba(185, 173, 80, 255), stop:0.16 rgba(136, 106, 22, 255), stop:0.225 rgba(166, 140, 41, 255), stop:0.285 rgba(204, 181, 74, 255), stop:0.482955 rgba(245, 236, 112, 255), stop:0.579545 rgba(187, 156, 51, 255), stop:0.635 rgba(168, 142, 42, 255), stop:0.695 rgba(202, 174, 68, 255), stop:0.75 rgba(218, 202, 86, 255), stop:0.815 rgba(208, 187, 73, 255), stop:0.886364 rgba(137, 108, 26, 255), stop:0.971591 rgba(187, 156, 51, 255), stop:1 rgba(209, 190, 76, 255));\n"
"color: rgb(255, 255, 255);"))
        self.btnStopwatch.setObjectName(_fromUtf8("btnStopwatch"))
        self.btnNewLap = QtGui.QPushButton(self.centralwidget)
        self.btnNewLap.setGeometry(QtCore.QRect(810, 200, 121, 41))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Lato"))
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.btnNewLap.setFont(font)
        self.btnNewLap.setObjectName(_fromUtf8("btnNewLap"))
        self.listView = QtGui.QListView(self.centralwidget)
        self.listView.setGeometry(QtCore.QRect(670, 250, 256, 261))
        self.listView.setObjectName(_fromUtf8("listView"))
        self.voltageBar = QtGui.QProgressBar(self.centralwidget)
        self.voltageBar.setGeometry(QtCore.QRect(150, 410, 151, 51))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Lato"))
        font.setPointSize(20)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        self.voltageBar.setFont(font)
        self.voltageBar.setStyleSheet(_fromUtf8("QProgressBar::chunk { background: green; margin:0.5px; width: 10px;}\n"
"QProgressBar {color: white; padding: 2px;}"))
        self.voltageBar.setMaximum(255)
        self.voltageBar.setProperty("value", 71)
        self.voltageBar.setAlignment(QtCore.Qt.AlignCenter)
        self.voltageBar.setObjectName(_fromUtf8("voltageBar"))
        self.label_25 = QtGui.QLabel(self.centralwidget)
        self.label_25.setGeometry(QtCore.QRect(10, 410, 131, 51))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Lato"))
        font.setPointSize(14)
        self.label_25.setFont(font)
        self.label_25.setStyleSheet(_fromUtf8("background: none;"))
        self.label_25.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_25.setObjectName(_fromUtf8("label_25"))
        self.frame = QtGui.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(0, 100, 281, 281))
        self.frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName(_fromUtf8("frame"))
        self.tempNumber = QtGui.QLabel(self.frame)
        self.tempNumber.setGeometry(QtCore.QRect(90, 20, 181, 201))
        font = QtGui.QFont()
        font.setPointSize(48)
        self.tempNumber.setFont(font)
        self.tempNumber.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.tempNumber.setStyleSheet(_fromUtf8("background: none;"))
        self.tempNumber.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.tempNumber.setObjectName(_fromUtf8("tempNumber"))
        self.label_21 = QtGui.QLabel(self.frame)
        self.label_21.setGeometry(QtCore.QRect(20, 210, 251, 81))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Lucida Console"))
        font.setPointSize(26)
        self.label_21.setFont(font)
        self.label_21.setStyleSheet(_fromUtf8("background-color: none;"))
        self.label_21.setObjectName(_fromUtf8("label_21"))
        self.label_20 = QtGui.QLabel(self.frame)
        self.label_20.setGeometry(QtCore.QRect(10, 20, 31, 201))
        self.label_20.setAutoFillBackground(False)
        self.label_20.setStyleSheet(_fromUtf8("background: none;"))
        self.label_20.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_20.setObjectName(_fromUtf8("label_20"))
        self.tempBar = QtGui.QGraphicsView(self.frame)
        self.tempBar.setGeometry(QtCore.QRect(50, 10, 41, 201))
        self.tempBar.setStyleSheet(_fromUtf8("background: transparent;"))
        self.tempBar.setObjectName(_fromUtf8("tempBar"))
        self.currentBar = QtGui.QProgressBar(self.centralwidget)
        self.currentBar.setGeometry(QtCore.QRect(150, 470, 151, 61))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Lato"))
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.currentBar.setFont(font)
        self.currentBar.setStyleSheet(_fromUtf8("QProgressBar::chunk { background: yellow; margin:0.5px; width: 10px;}\n"
"QProgressBar {color:black; padding: 2px;}"))
        self.currentBar.setMaximum(255)
        self.currentBar.setProperty("value", 24)
        self.currentBar.setAlignment(QtCore.Qt.AlignCenter)
        self.currentBar.setObjectName(_fromUtf8("currentBar"))
        self.label_26 = QtGui.QLabel(self.centralwidget)
        self.label_26.setGeometry(QtCore.QRect(10, 470, 131, 51))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Lato"))
        font.setPointSize(14)
        self.label_26.setFont(font)
        self.label_26.setStyleSheet(_fromUtf8("background: none;"))
        self.label_26.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_26.setObjectName(_fromUtf8("label_26"))
        self.btnConnect = QtGui.QPushButton(self.centralwidget)
        self.btnConnect.setGeometry(QtCore.QRect(10, 0, 141, 41))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Lato"))
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.btnConnect.setFont(font)
        self.btnConnect.setStyleSheet(_fromUtf8("background-color: qconicalgradient(cx:0.5, cy:0.5, angle:0, stop:0.113636 rgba(185, 173, 80, 255), stop:0.16 rgba(136, 106, 22, 255), stop:0.225 rgba(166, 140, 41, 255), stop:0.285 rgba(204, 181, 74, 255), stop:0.482955 rgba(245, 236, 112, 255), stop:0.579545 rgba(187, 156, 51, 255), stop:0.635 rgba(168, 142, 42, 255), stop:0.695 rgba(202, 174, 68, 255), stop:0.75 rgba(218, 202, 86, 255), stop:0.815 rgba(208, 187, 73, 255), stop:0.886364 rgba(137, 108, 26, 255), stop:0.971591 rgba(187, 156, 51, 255), stop:1 rgba(209, 190, 76, 255));\n"
"color: rgb(255, 255, 255);"))
        self.btnConnect.setObjectName(_fromUtf8("btnConnect"))
        self.label_27 = QtGui.QLabel(self.centralwidget)
        self.label_27.setGeometry(QtCore.QRect(170, 0, 81, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Lato"))
        font.setPointSize(16)
        self.label_27.setFont(font)
        self.label_27.setStyleSheet(_fromUtf8("background: none;"))
        self.label_27.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_27.setObjectName(_fromUtf8("label_27"))
        self.labelStatus = QtGui.QLabel(self.centralwidget)
        self.labelStatus.setGeometry(QtCore.QRect(260, 0, 141, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Lato"))
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.labelStatus.setFont(font)
        self.labelStatus.setStyleSheet(_fromUtf8("background: none;\n"
"color: rgb(255, 0, 0);"))
        self.labelStatus.setObjectName(_fromUtf8("labelStatus"))
        self.framesLabel = QtGui.QLabel(self.centralwidget)
        self.framesLabel.setGeometry(QtCore.QRect(230, 40, 451, 51))
        self.framesLabel.setObjectName(_fromUtf8("framesLabel"))
        self.dial = QtGui.QDial(self.centralwidget)
        self.dial.setGeometry(QtCore.QRect(380, 420, 181, 111))
        self.dial.setMaximum(255)
        self.dial.setSingleStep(1)
        self.dial.setObjectName(_fromUtf8("dial"))
        self.pushButton = QtGui.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(540, 430, 75, 23))
        self.pushButton.setObjectName(_fromUtf8("pushButton"))
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 960, 27))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow", None))
        self.label_23.setText(_translate("MainWindow", "Battery:", None))
        self.btnStart.setText(_translate("MainWindow", "START", None))
        self.label_24.setText(_translate("MainWindow", "Laptime", None))
        self.timeEdit.setDisplayFormat(_translate("MainWindow", "HH:mm:ss", None))
        self.btnStopwatch.setText(_translate("MainWindow", "Start", None))
        self.btnNewLap.setText(_translate("MainWindow", "New lap", None))
        self.voltageBar.setFormat(_translate("MainWindow", "%v V", None))
        self.label_25.setText(_translate("MainWindow", "Battery Voltage", None))
        self.tempNumber.setText(_translate("MainWindow", "<html><head/><body><p>0 <span style=\" vertical-align:super;\">o</span>C</p></body></html>", None))
        self.label_21.setText(_translate("MainWindow", "Engine temp.", None))
        self.label_20.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:9pt;\">250<br/><br/><br/>187.5<br/><br/><br/>125<br/><br/><br/>62.5<br/><br/><br/>0</span></p></body></html>", None))
        self.currentBar.setFormat(_translate("MainWindow", "%v A", None))
        self.label_26.setText(_translate("MainWindow", "Battery Current", None))
        self.btnConnect.setText(_translate("MainWindow", "Connect", None))
        self.label_27.setText(_translate("MainWindow", "Status: ", None))
        self.labelStatus.setText(_translate("MainWindow", "Not connected", None))
        self.framesLabel.setText(_translate("MainWindow", "TextLabel", None))
        self.pushButton.setText(_translate("MainWindow", "PushButton", None))

